### ISSUE TITLE
Doc cl.rst could be broken into sections

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#118]
*  Commands for installing and upgrading:
  *  Commands for working with the data and marking that you want actions to happen:
  *  Commands for processing actions that have been marked as should doing with the data:

Make it easier for people using the hosted section to easily scan and see which commands they should be using (the middle section) and which they shouldn't (the other 2 sections)

**Comment by jpmckinney** [comment]
Assuming closed by #119
