### ISSUE TITLE
Compiled Releases Transform does not store what schema/extensions/versions was used

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#12]
When #11 is done ....

The Complied Releases Transform might be using custom schema/extensions/versions configurations. It would be good to save what schema/extensions/versions were used alongside the actual Complied Release data. Analysts can use this data to do better analysis.

In other cases, this is done in the package format - but we don't have a package spec for compiled releases.

**Comment by jpmckinney** [comment]
Duplicate #122 which goes into more detail.
