### ISSUE TITLE
Support list of releases data model

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-process#133]
Indonesia has now a service that returns releases in a list: [{release1}, {release2}] example: 
https://webhooks.mongodb-stitch.com/api/client/v2.0/app/birms-cvrbm/service/query-birms/incoming_webhook/find-releases?secret=6WkBFKh6SS4ibE2O0Fm5UHGEQWv8hQbj&fromId=5be21cf4bdd6426122ce6f81

So we need to support releases_list also https://kingfisher-process.readthedocs.io/en/latest/data-model.html#data-types-for-files

**Comment by odscjames** [comment]
Thanks for report - this seems a clearly defined thing to add.
