### ISSUE TITLE
New Collection command does not respect deleted collections!

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#141]
```
$ python ocdskingfisher-process-cli upgrade-database --deletefirst
Dropping Database
Dropping Redis
Upgrading/Creating Database
$ python ocdskingfisher-process-cli list-collections
DB-ID SOURCE-ID                                DATA-VERSION         SAMPLE TRANSFORM            FROM  DELETED 
$ python ocdskingfisher-process-cli new-collection my-own-source-id  "2019-01-20 10:00:12"
Created! The ID is 1
$ python ocdskingfisher-process-cli list-collections
DB-ID SOURCE-ID                                DATA-VERSION         SAMPLE TRANSFORM            FROM  DELETED 
    1 my-own-source-id                         2019-01-20 10:00:12  Full  -                          -      
$ python ocdskingfisher-process-cli delete-collection 1

$ python ocdskingfisher-process-cli list-collections
DB-ID SOURCE-ID                                DATA-VERSION         SAMPLE TRANSFORM            FROM  DELETED 
    1 my-own-source-id                         2019-01-20 10:00:12  Full  -                          DELETED
$ python ocdskingfisher-process-cli new-collection my-own-source-id  "2019-01-20 10:00:12"

Already exists! The ID is 1
```

I'm not sure what should happen in this case!

**Comment by jpmckinney** [comment]
Do we want to allow an "undo-delete-collection" command, if the user really wants to have the exact same data version? Otherwise, they can just add a second to the data version.

I think things would get complicated if we were to allow multiple deleted collections with the same identifying columns.

**Comment by odscjames** [comment]
That's not the only reason; also it means if Collection A has Collection B as a transform from it, you can delete the data from A whilst leaving B, the record of where B came from, and all notes. Maybe this isn't an important use case tho. (I suppose if there was a tree of transformed collections, and all of them were deleted, you could delete the collection rows after.)

We will also need some kind of flag like deleted_at - even if it only took minutes to run the actual delete, there would still be a period of time where you want to make sure no other action (like create a new transform) is allowed.

I guess the first step is just to raise an error if this situation happens; at least then people won't continue and wonder why weird things are happening, and we can start to collect some user feedback on if this ever actually occurs enough to stress about. Such error raising would need to happen in both the CLI and Web API.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise error if a Kingfisher collection is created that matches a existing deleted collection to fix edge case](https://trello.com/c/YsBskC15/56-raise-error-if-a-kingfisher-collection-is-created-that-matches-a-existing-deleted-collection-to-fix-edge-case)

**Comment by jpmckinney** [comment]
The current behavior is that `new-collection` reports an ID, even though that ID is deleted. I suppose the desired behavior is for it to say that the ID is deleted (which is less confusing).

In the Django branch, there won't be a separate new-collection command. Instead, there's just `load` to add data (and choose transforms) and `addstep` to add transforms to an existing collection. If `load` would create a duplicate collection, it errors instead.

For the web API, two people would have to start crawls in the same second for there to be a collision. To prevent that, we'd need a new "start collection" endpoint, that gets called when a spider is opened. In the case where a collection already exists, the spider would close immediately. I've created a new issue for that: #270
