### ISSUE TITLE
Edge case if delete transform and create it again

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#142]
* Create source collection (1)
* Create destination upgrade 1.0 to 1.1 collection (2)
* It does work
* Delete collection (2)
* Create another destination upgrade 1.0 to 1.1 collection (3)
* It tries to work

I think this will fail to work because the transform_upgrade_1_0_to_1_1_status_record and  transform_upgrade_1_0_to_1_1_status_release tables will still have values in - so the transform will think it's work is done and not do anything!

But also, see #141 - this might break at the second last step anyway!

**Comment by jpmckinney** [comment]
See https://github.com/open-contracting/kingfisher-process/issues/141#issuecomment-490158460 as the solution might just be to make deletion fast and do away with storing deleted collections forever.

**Comment by odscjames** [comment]
Unfortunately it's a bit more complex than that - transform_upgrade_1_0_to_1_1_status_release and transform_upgrade_1_0_to_1_1_status_record tables  have source_release_id and source_record_id rows. When the transform is deleted, the rows that match the source collection data have to be deleted too. 

Again, I guess the first step is just to raise an error if this situation happens; at least then people won't continue and wonder why weird things are happening, and we can start to collect some user feedback on if this ever actually occurs enough to stress about. Such error raising would need to happen in the CLI only; I think it should be impossible for this situation to arise via the standard pipeline.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raise error if a Kingfisher collection is created that matches a existing deleted collection to fix edge case](https://trello.com/c/YsBskC15/56-raise-error-if-a-kingfisher-collection-is-created-that-matches-a-existing-deleted-collection-to-fix-edge-case)

**Comment by jpmckinney** [comment]
The Django branch won't use the database as a queue (it won't have `transform_upgrade_1_0_to_1_1_status_release` and `transform_upgrade_1_0_to_1_1_status_record` tables). Its `addstep` command (for adding transforms) will error correctly if the parent collection is being deleted. There is already a test: https://github.com/open-contracting/kingfisher-process/blob/django/process/tests/commands/test_addstep.py#L73-L83
