### ISSUE TITLE
Report exceptions to Sentry (if not properly handled)

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#149]
See like https://github.com/open-contracting/kingfisher-process/blob/06610306742c2ee37a9d46fba0f0805c30d480a2/ocdskingfisherprocess/cli/commands/transform_collections.py#L40 does.

The reason for this is that it makes more information available to developers who have been asked to debug problems seen on live.

**Comment by jpmckinney** [comment]
Can I be given access to Sentry?

**Comment by odscjames** [comment]
That should be fine - which email address do you want to use?

**Comment by jpmckinney** [comment]
My regular OCP address, please: jmckinney@open-contracting.org

**Comment by jpmckinney** [comment]
Noting that such exceptions should also be logged as described in #242.

**Comment by jpmckinney** [comment]
All exceptions are now logged in Sentry (in fact, sometimes, too many!).
