### ISSUE TITLE
Collection / collection file currently have store started / store ended at fields - deal with these correctly

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#15]
Collection / collection file tables currently have store started / store ended at fields. This was a hangup from old system.

We still want something that tracks the finished status of a collection - it is needed for things like #13 Therefore we probably want something that tracks the finished state of a file too.

The names are a hangup from what we had before. Do we still want these fields and these names? I think so. The word "store" makes clear that it's the actual storing of data we are tracking and not other operations you would carry out on data, such as checks or transforms.

But in that case, we need to go through and make sure the correct data is being written to these fields. (That will probably mean adding a new HTTP APi end point that Scrapy can call to say when it's finished.)

**Comment by odscjames** [comment]
Let's try and deal with these correctly.

That commit adds a new HTTP API method to report a collection has finished storing. 

After that
  *  when collection ended, end all open files too. (there is a TODO in database)
  *  enforce that store actions (API and local load) can't happen after a collection is ended
  *  need a CLI command too, to end collection storage. A user might need to use this after a local load but before starting a transform.
  *  start on #13

**Comment by jpmckinney** [comment]
Do we need store_start_at and store_end_at on collection_file and collection_file_item? I don't think there is any present or anticipated logic that depends on them. Also, for the purpose of measuring performance, I don't think that we need timing information at the level of the file and file item.

We need store_start_at on collection as an indication of the time at which it was collected/loaded (in addition to data_version, which, if loading an archived file, might be set to a year earlier), and we need a way to indicate that a collection is closed/done for the compile-releases transform to run. While we could just have a boolean, store_end_at is nice for understanding the time operations take.

So, unless we have real use cases, I'm in favor of removing store_start_at and store_end_at from collection_file and collection_file_item.

**Do any helpdesk analysts have a use for these fields?** (raising in weekly call)

**Comment by romifz** [comment]
> **Do any helpdesk analysts have a use for these fields?**

I don't.

**Comment by yolile** [comment]
> Do any helpdesk analysts have a use for these fields? (raising in weekly call)

I've never used those fields.

**Comment by duncandewhurst** [comment]
I don't need them either

**Comment by pindec** [comment]
I only use them on collection for the reasons @jpmckinney noted.
