### ISSUE TITLE
Redis is full of duplicate messages

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#151]
First I noticed that we had a ton of cron mail. Much of the mail is days and days of the same message, which is tons of repetitions of:

```
Got Message: {"type": "collection-data-store-finished", "collection_id": 222}
Processed!
```

Doing some exploring on the server:

```python
import json

import redis

connection = redis.Redis()
connection.llen('kingfisher_work')
# 36014861
messages = connection.lrange('kingfisher_work', 0, -1)
messages = [json.loads(message) for message in messages]
len([message['type'] == 'collection-data-store-finished' for message in messages])
# 36014861
len({message['collection_id'] for message in messages if message['type'] == 'collection-data-store-finished'})
# 89
```

So, we have 36 million 'collection-data-store-finished' messages for 89 collection IDs… In practice, I think this means that the process-redis-queue command will never be able to clear out the messages.

I think a consequence is that the server is under never-ending high load, as it repeatedly tries to check the same collection hundreds of thousands of times…

Something about the 'collection-data-store-finished' signal seems broken… I think there should at most be one such message per collection in Redis at any given time.

Can we address this issue with some urgency?

**Comment by odscjames** [comment]
I thought we already had done something to address this, but now I take a quick look I can't find it. I will try to have a look soon.

**Comment by odscjames** [comment]
Our preferred solution for this is to change the message that is sent such that it doesn’t just have collection ID, but has the specific files that were just uploaded. This means
* no more duplicate messages!
* handling each message is faster - you just check file, not whole collection at once so que will clear faster.
* much better parallelisation is possible. 2 fies uploaded at once, 2 workers can check each file at the same time!

However given the 36M backlog we will probably tackle this problem in stages.

**Comment by odscjames** [comment]
The duplicate fix has been deployed; now we should look at removing existing messages.

**Comment by jpmckinney** [comment]
Yes, makes sense for (1) `with DatabaseStore` blocks to `__exit__` by enqueuing the files that were processed, and not the collection as a whole and (2) for `ProcessQueueMessage` to not process all files but only the files referenced in the dequeued message.

I notice that LPUSH and BLPOP are used, which means that the list is being used as a stack (last-in, first-out) instead of as a queue (first-in, first-out). This means that work that was scheduled earliest will be done last… Shouldn't we use a combination like RPUSH and BLPOP?

To remove existing duplicates, I think you can activate the venv on the server and run:

```python
import json

import redis

pipeline = redis.Redis().pipeline()
messages = pipeline.lrange('kingfisher_work', 0, -1)
messages = list(set(messages))
pipeline.del('kingfisher_work')
pipeline.rpush('kingfisher_work', *messages)
pipeline.execute()
```

**Comment by odscjames** [comment]
I have cleared out and repopulated the que.

> which means that the list is being used as a stack (last-in, first-out)

We'll check that.

**Comment by jpmckinney** [comment]
I deleted the 773 mail messages from before.

**Comment by odscjames** [comment]
Think this can now be closed? We have done the work described in 9th May comment and as part of that changed it to a que not a stack.
