### ISSUE TITLE
Redis: More efficient duplication avoidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#154]
#153 uses LREM which is O(n) for the size of the list. If the Redis queue gets very long, this becomes increasingly time-expensive.

An alternative is to have a list and a set. In pseudo-code, when adding to the queue:

```
if not SISMEMBER kingfisher_work_set {…}
    SADD kingfisher_work_set {…}
    LPUSH kingfisher_work {…}
```

When de-queuing, you'll need to SREM from the set the value that you BLPOP from the list.

All these operations are O(1).

**Comment by odscjames** [comment]
This is a good technical solution but I'm actually hoping we can avoid it - currently, the size of the que is bounded by the number of collections, so O(n) is fine.

In the future, we have talked about moving to more fine-grained messages that by definition won't be duplicates - https://github.com/open-contracting/kingfisher-process/issues/151#issuecomment-490869473 These will be much faster to process so the que size should not get massive, tho it may get big - but at this point I'm hoping we can just drop LREM entirely, as by definition all messages should be unique anyway.

**Comment by jpmckinney** [comment]
Good point! Closing.
