### ISSUE TITLE
Ways for people to get CSVs out of Kingfisher

### ISSUE THREAD

**Issue by robredpath** [open-contracting/kingfisher-process#170]
During the Researchers/Academics data use training in Nottingham in June 2019, we saw that, while Kingfisher represents the removal of a large barrier to data use, the final stage of getting data in a flat format for analysis was still a challenge. 

Currently, users can:
- Query the data, and get JSON back, then run it through flatten-tool to flatten it
- Construct SQL queries that extract the data they're interested in into a tabular form
- Use the exporters that we've made for Colab - https://drive.google.com/drive/folders/1ETQbwyUqASizyDWitL7v2VmfbFge8ZcW

It may be sufficient to document/release these. Or, we might want to do some more work on kf-process to remove some of these barrier - such as through saved queries, new cmdline functions, or a different interface.

**Comment by jpmckinney** [comment]
This will be superseded by the data registry/data service.

The idea is for KFP to pre-process data up to compiled releases, and then for the data service to allow the user to select the data they want (choosing columns and filtering rows) and export it using an improved flattening tool.
