### ISSUE TITLE
Transforms - log crashes in transform, log in DB for analysts to see, try and continue with other work of transform

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#172]
Inspired by https://github.com/open-contracting/kingfisher-process/issues/147

Currently, if a transform crashes it is caught at the level of the collection. Processing continues with the next collection and no good log is made for the analysts.

It would be better if a crash while processing one unit of work in the transform did not stop other units of work being run.

It would be better if it was logged somewhere analysts could see, so that they can report easily. But have to make sure that if the code is then fixed so that the error clears, and the transform now works, that error logging still makes sense.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kingfisher Process Transforms - log crashes in transform, log in DB for analysts to see, try and continue with other work of transform](https://trello.com/c/qO4iFvCH/36-kingfisher-process-transforms-log-crashes-in-transform-log-in-db-for-analysts-to-see-try-and-continue-with-other-work-of-transfo)

**Comment by jpmckinney** [comment]
From Trello:

@jpmckinney:

> I think the error handling solution depends on what changes we make to how messages and workers are managed for transforms.

@odscjames:

> Not sure how the workers will affect this. I think the resolution to #147 might have some affect tho.

Quick answer: Let's say that a transform worker is designed to pull one item of work at a time from a queue, and that it either puts the result into a results queue for storage in the database, or puts an error in an error queue for handling. That would obviously require a different error handling approach than if we kept the current architecture of a single script that, each time, iterates over all collections with a `transform_type` and without a `deleted_at` or `store_end_at`, and then iterates over all files, items, and rows in the collection to see if they need to be processed, and then processes the row.

**Comment by jpmckinney** [comment]
I'll create a new issue to describe what should be the common behaviors across workers (e.g. handle unexpected errors gracefully and continue work if possible).

Overlaps with #149 and #242.
