### ISSUE TITLE
Other ways to run Checks/Transforms

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#18]
Checks and Transforms are currently run by the check-collection and transform-collection command. This is clunky as you have to run that command by hand, and you have to run it for each collection individually.

(Note in this case "Run" and "enable/disable" the task happening are different things. In the case of checks you enable them for a collection by setting a flag in that table and in the case of a transform you enable it by creating a new collection with the transform settings. Other issues deal with those processes. But then you actually have to run the code that does the work, and that's what this issue is about.)

Discuss/Plan better ways of running those tasks so that they run automatically and operators don't have to start them by hand each time.

**Comment by jpmckinney** [comment]
Issue description is closed by related commits.
