### ISSUE TITLE
VACUUM ANALYZE after deletion, or set auto-vacuum variables

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#180]
Without this, performance will deteriorate on the largest tables, because the dead rows will continue to be scanned during full-table scans.

Right now we have millions of dead rows in release, release_check and transform_upgrade_1_0_to_1_1_status_release.

```sql
SELECT relname, n_dead_tup FROM pg_stat_user_tables WHERE n_dead_tup != 0;
```

```
                   relname                   | n_dead_tup 
---------------------------------------------+------------
 collection_file_item                        |       9289
 record                                      |       1603
 record_check                                |       3206
 transform_upgrade_1_0_to_1_1_status_release |    9001482
 release                                     |   13144203
 collection_file                             |       7722
 collection                                  |         21
 release_check                               |   13049874
(8 rows)
```

**Comment by odscjames** [comment]
Auto-vacuum should be on - I actually checked that a few days ago, because I was aware the delete work I was doing may cause this situation. Let's keep an eye on this over the next few week or two.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure delete is working well in Kingfisher Process](https://trello.com/c/iN5iQ7Ye/79-make-sure-delete-is-working-well-in-kingfisher-process)

**Comment by odscjames** [comment]
Can verify autovac should be on:

> 
> ocdskingfisherprocess=> SELECT * FROM pg_settings where name like '%autovac%';
> ocdskingfisherprocess=> SELECT * FROM pg_settings where name like '%track_counts%';

But it's not doing much at all: 

    select relname, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze from
    "pg_catalog"."pg_stat_all_tables" where schemaname='public';

Don't know why - that's a mystery. Now doing some vacums by hand.

**Comment by odscjames** [comment]
@kindly Has pointed out autovacuum_vacuum_scale_factor is currently 20% and those tables did not reach 20% yet - we will consider changing that after some manual runs

**Comment by jpmckinney** [comment]
Autovaccum and autoanalyze seem to be working well.

```sql
SELECT relname, n_live_tup, n_dead_tup, n_dead_tup * 1000 / GREATEST(n_live_tup, 1) permille, last_vacuum, last_autovacuum, last_analyze, last_autoanalyze FROM pg_stat_user_tables WHERE schemaname = 'public' ORDER BY last_autoanalyze;
```
