### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by Vferth** [open-contracting/kingfisher-process#188]
I am runing 'pip install -r requirements.txt' on Ubuntu 18.04.1 LTS and getting the following error:

> (.ve) root@vps45929793:~/kingfisher/kingfisher-process-master# pip install -r requirements.txt
Collecting flattentool==0.8.0 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/09/aa/73e95432c6ef32b9e4ccc667ce0bb30fa596dcf2e109607700369680b321/flattentool-0.8.0-py3-none-any.whl
Collecting libcove==0.10.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/e1/33/8d1003ca582c1a0193c463cc0f16b3dd090b26e0fa10de1c9548598acf2c/libcove-0.10.0.tar.gz
Collecting libcoveocds==0.7.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/3a/1b/3a9ba6fc66cb126e8c667b433c77a53cfc8c87618a4a51c49d5697c0b0c8/libcoveocds-0.7.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /root/.ve/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ifw25pvv/libcoveocds/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ifw25pvv/libcoveocds/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-ifw25pvv/libcoveocds/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ifw25pvv/libcoveocds/setup.py", line 4, in <module>
        long_description = f.read()
      File "/root/.ve/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 658: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

can anyone help, thanks

**Comment by robredpath** [comment]
Hi @Vferth - thanks for letting us know about this! I'd love to hear more about how you're hoping to use Kingfisher - if you'd like, could you drop an email to data@open-contracting.org letting us know how you're planning to use it, and what you're up to with OCDS data? We always love to hear about what people are up to, and we'll see if it's something we can help with in other ways, as well. 

In the meantime, let's get you set up. I just tried installing on my 18.04 box and it worked just fine (although I'm running 18.04.3 LTS - maybe that point release gives us something?). @jpmckinney did recently refactor the requirements setup on `lib-cove-ocds` to use `setup.py` so over to him first of all to see if he can shed any light!

**Comment by jpmckinney** [comment]
Hi @Vferth, thanks for reporting the issue!

I released a version 0.7.3 of libcoveocds which should correct this issue. Please try again with `pip install --upgrade -r requirements.txt`

Fixed in https://github.com/open-contracting/lib-cove-ocds/commit/f596eb27b6e5b1aa2396fd15e40254f227b8140a

**Comment by jpmckinney** [comment]
@Vferth It seems like your default system encoding is ascii. To avoid similar, future issues, please set it to UTF-8. See, for example, https://perlgeek.de/en/article/set-up-a-clean-utf8-environment
