### ISSUE TITLE
Allow prioritizing collections

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#190]
Currently work is done on collections in an order the user can't control.

Allow the user to be able to prioritise work on certain collections.

(From discussion around https://github.com/open-contracting/kingfisher-process/pull/152#issuecomment-491908018 )

**Comment by jpmckinney** [comment]
The new Kingfisher Process is so far, that prioritization is unnecessary.

**Comment by jpmckinney** [comment]
Noting that checks are still slow, but rather than prioritization, I think we need to be more selective (https://github.com/open-contracting/kingfisher-collect/issues/861) or take samples #346 .
