### ISSUE TITLE
Use fanout (pub/sub) pattern to automate processing by Kingfisher Views, Pelican

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#193]
This gives us the option of doing things with a multi-subscriber architecture later, instead of the current single subscriber architecture.

( From discussion from https://github.com/open-contracting/kingfisher-process/pull/152#issuecomment-491908018 )

**Comment by odscjames** [comment]
One consideration is that if a message is sent when no worker is currently running, the message will sit there until a worker runs. I think with pub/sub that wouldn't be the case? Have to decide if that is an issue.

**Comment by jpmckinney** [comment]
For now, we only want to use pub/sub for #183 (in the context of notifying Kingfisher Views or the Data Quality Tool that a collection is done), where if there is no worker to pick up the work, then that's fine.

For #183, in terms of calculating the counts, we can either have the 'counts' worker subscribe to the same channel, or we can use a queue for the counts worker (in which case, we're sending a message to two queues/channels – a queue for KF-internal work, and a pub/sub channel for external subscribers).

**Comment by jpmckinney** [comment]
Closing in favor of #296.
