### ISSUE TITLE
Remove Sphinx from test section in extras_require

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#196]
It's not used for testing (slows down Travis), only for docs. It was originally moved from requirements_dev.in, which ostensibly was for both testing and docs.

**Comment by jpmckinney** [comment]
In light of #195, this would instead be for it not to be a dev dependency (or, at minimum, not something that is installed on Travis CI).

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)
