### ISSUE TITLE
SQLAlchemy version pinned but needs upgrading

### ISSUE THREAD

**Issue by rhiaro** [open-contracting/kingfisher-process#197]
SQLAlchemy is only used for the old scrapers. If they all get ported before this is fixed, this issue can be closed.

There are security warnings that say SQLAlchemy needs to be upgraded past 1.3.0 but we currently have it pinned at 1.2.19 because "1.3 branch has issues with an identifier being too long"

We should locate the source of this problem and fix it so we can upgrade SQLAlchemy.

**Comment by jpmckinney** [comment]
Since we plan on porting all scrapers, let's do that and dismiss the security warning.

**Comment by rhiaro** [comment]
Sounds good to me!
