### ISSUE TITLE
Delete setup.py

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#200]
Blocked by https://github.com/open-contracting/kingfisher-views/issues/34 (also still needed to test Views)

Follow-up to #195

**Comment by odscjames** [comment]
Note additional problem noted in https://github.com/open-contracting/kingfisher-views/pull/40#issuecomment-539050394 - setup.py is needed for the Travis tests in kf-views and thus can't be deleted yet!

**Comment by odscjames** [comment]
Blocked by https://github.com/open-contracting/kingfisher-views/issues/41

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)
