### ISSUE TITLE
Move update_requirements.sh to another repo

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#201]
Follow-up to #195

This would just be a common script we can `curl http://url.for/script | bash -` instead of having it in lots of repos. The common repository can be https://github.com/open-contracting/standard-maintenance-scripts, putting the script in a new `scripts/` directory.

----

Regarding the script itself, OCP doesn't use requires.io, instead using GitHub security alerts, so the last lines of the current script can be removed. https://github.com/open-contracting/lib-cove-ocds/pull/28 also noted:

* The script doesn't work on macOS (`sed -i` needs to be `sed -i ""`)
* The first three lines assume that the developer created a virtualenv in `.ve` with the `virtualenv` command from the `virtualenv` package. It doesn't work if the user uses `pyenv` or similar to manage virtualenvs. Repos shouldn't have an opinion on how developers manage their virtualenvs.

**Comment by jpmckinney** [comment]
Regarding how many files this script ought to manage, https://github.com/open-contracting/lib-cove-ocds/pull/28 proposed having only:

* `requirements.in` for direct dependencies, with loose versions
* `requirements.txt` for all production dependencies, with fixed versions

Presently, we also have a pair of `requirements_dev` files with loose and fixed versions. However, as discussed in https://github.com/open-contracting/lib-cove-ocds/pull/28#issuecomment-533618374, there are fewer advantages to having fixed versions for development dependencies, and some disadvantages.

Instead, we can have one `requirements-dev.txt` file for all development/test dependencies, with loose versions (filename uses hyphen, not underscore, which is more common across other Python repos and thus more predictable). 

The present `requirements_dev.txt` also includes all production dependencies, presumably to allow developers to `pip install` one requirements file instead of two. I prefer to keep it to just the additional development dependencies, which is how most other projects I've seen do it.

**Comment by jpmckinney** [comment]
Alternately – should we just use pip-compile from https://pypi.org/project/pip-tools/ ? Seems much easier! pip-sync is also handy.

**Comment by jpmckinney** [comment]
In terms of documentation, we can put a link to new handbook docs at the top of `requirements.in`. (This is better than putting docs in a readme or elsewhere.)

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure Python dependencies are working, including knock on effects](https://trello.com/c/0mawoVXt/116-make-sure-python-dependencies-are-working-including-knock-on-effects)

**Comment by robredpath** [comment]
> Alternately – should we just use pip-compile from https://pypi.org/project/pip-tools/ ? Seems much easier! pip-sync from pip-tools is also handy.

@jpmckinney we've been talking about switching to Poetry (https://poetry.eustace.io/) internally, so this is a timely consideration! I've opened https://github.com/open-contracting/kingfisher/issues/329 for want of somewhere sufficiently abstract to properly place the issue, and @odscjames is planning to comment later today with some initial thoughts. If you're up for it, we could then have a call in a couple of weeks' time to discuss and decide. 

In the short term, however, we'll just do what the issue title suggests.

**Comment by odscjames** [comment]
Yes, lets split this into 2 and recognise that in the short-term we have requirements.in/.txt files and make sure we handle them well in this ticket. I've commented on the other ticket about medium-term solutions.

> OCP doesn't use requires.io, instead using GitHub security alerts,

We started using requires.io before GitHub security alerts was a thing; we have been phrasing it out. So I think we'd be happy to just remove it at this point.

> Presently, we also have a pair of requirements_dev files with loose and fixed versions.

I would comment that your objection to these is maybe more from the experience of working alone or with fewer developers. When we have a larger team/community of developers, as we often do, and as OCP are looking to do more in the future I believe, it really pays to have standard environments between different developers, and also between them and Travis. Also, in this environment keeping branches simple and focused really helps when multiple developers work on the same repository, and I worry that with developers having to fix minor upgrade issues as they work on other issues this becomes more difficult.  However, I'm also pretty certain that whatever we pick as a medium-term solution in https://github.com/open-contracting/kingfisher/issues/329 will touch on this, and will maybe sweep these files away anyway, so I wouldn't want to spend much time on this now.

> The first three lines assume that the developer created a virtualenv in .ve

At the end of the day, as long as the developer properly updates .in and then .txt it doesn't matter which method they use. We traditionally provided this script as a handy way to do that, but we are also happy to make sure the goals are properly documented somewhere (standard handbook?) and as long as the developer achieves those, it doesn't matter what method they use.

> Move update_requirements.sh to another repo
> we can put a link to new handbook docs at the top of requirements.in.

Let's do this, do you have a suggestion of which repo?

**Comment by odscjames** [comment]
> I think this other point can still be done:
>
>>    The present requirements_dev.txt also includes all production dependencies, presumably to allow developers to pip install one requirements file instead of two. I prefer to keep it to just the additional development dependencies, which is how most other projects I've seen do it.

Quick message after meeting; Let me check this, as I'm not sure what the update process would be.

@rhiaro has pointed out that the comment in https://github.com/OpenDataServices/cove/blob/master/update_requirements.sh#L33 says "mainly for requires.io" but there are other reasons to keep comments in requirements.txt. Let us check that as well.

**Comment by jpmckinney** [comment]
I'm happy with just looking at the comments in `requirements.in`. I guess it's nice to have them copied over, but I treat `requirements.txt` as just the output of `pip freeze`.

**Comment by odscjames** [comment]
> I'm happy with just looking at the comments in requirements.in.

Ok

> Keeping a pair of dev files sounds good. I think this other point can still be done:
>    The present requirements_dev.txt also includes all production dependencies, presumably to allow developers to pip install one requirements file instead of two. I prefer to keep it to just the additional development dependencies, which is how most other projects I've seen do it.

We have traditionally done it this way, I think to make sure the dev environment follows on from live properly. If we had only dev requirements in requirements_dev.txt, in order to generate it we would have to 

* create a new empty virtual env, 
* run just pip install req.in, 
* then freeze to req.txt. 
* delete and create a new empty virtual env, 
* run just pip install req_dev.in, 
* then freeze to req_dev.txt. 

However, there may be a complication if 2 things in req.in and req_dev.in both have the same common dependency, and somehow pip decides to install different versions. I may be wrong here, but given that we are about to review and probably change all of this anyway in https://github.com/open-contracting/kingfisher/issues/329 I personally would be happy sticking with what we know, as there may be small problems lurking if we change now. Does that sound good?

I done 2 pull requests for this with that assumption for your review (and we can can tweak if needed), should be linked to this ticket.

**Comment by jpmckinney** [comment]
Yes, sounds good – we want to avoid version conflicts between the two files.

**Comment by odscjames** [comment]
I think this can be closed now?

**Comment by jpmckinney** [comment]
Yes, all above comments either addressed or part of https://github.com/open-contracting/kingfisher/issues/329
