### ISSUE TITLE
Install ocdskit and jq on the hosted kingfisher process server

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#203]
When publishers send a link to a large bulk file it is easier to download this directly onto the hosted kingfisher process server so it can be local loaded.

However sometimes the file(s) need manipulating before they can be loaded and in those cases it would be useful to have ocdskit and jq on the server.

**Comment by odscjames** [comment]
Sounds sensible and really shouldn't take long. I won't even try Friday afternoon from a train tho.

**Comment by robredpath** [comment]
kingfisher-analyse is probably the place for these. We install that bundle alongside kingfisher-process but it keeps the two functions separate, at least in theory

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Install tools on Kingfisher server](https://trello.com/c/51HD7wKH/128-install-tools-on-kingfisher-server)

**Comment by odscjames** [comment]
Done and on server. jq is for all users, flatten tool and ocdskit can be found under the the analysis user's home directory

**Comment by duncandewhurst** [comment]
thanks @odscjames 

I tried to connect as the analysis user using the command in the [hosted kingfisher docs](https://ocdskingfisher.readthedocs.io/en/latest/hosted.html#access-for-analysis) but I got the following error:

```bash
ssh analysis@analyse.kingfisher.open-contracting.org
ssh: Could not resolve hostname analyse.kingfisher.open-contracting.org: Name or service not known
```

Once connected as the analysis user is it possible to local load files into kingfisher process? (my original need was to use ocdskit on a file before local-loading it)

**Comment by jpmckinney** [comment]
I added the DNS entry, but for now you can just ssh `analysis@process.kingfisher.open-contracting.org` (they are the same server, so there is no difference).

**Comment by duncandewhurst** [comment]
thanks @jpmckinney 

I've connected with those details and can see the ocdskit folder but the cli wasn't available, so I've installed it via pip3

**Comment by odscjames** [comment]
It was in a virtual env:

```
analysis@process:~/ocdskit$ source .ve/bin/activate
(.ve) analysis@process:~/ocdskit$ ocdskit
usage: ocdskit [-h] [--encoding ENCODING] [--ascii] [--pretty]
               {combine-record-packages,combine-release-packages,compile,detect-format,indent,mapping-sheet,package-releases,schema-report,schema-strict,set-closed-codelist-enums,split-record-packages,split-release-packages,tabulate,upgrade,validate}
               ...

```

https://github.com/open-contracting/kingfisher/pull/330 adds docs on this and and your other question.

It's maybe a fair point that analysis user and the process user should just be the same user - make another issue if this is wanted?

**Comment by duncandewhurst** [comment]
I think having the analysis user is a useful resource for helpdesk analysts when they want to do something that needs more resources than their local machine (or a colab notebook) can provide, but I also think having all 3 of those tools available to the process user (on the command line ideally) would make local loading data into kingfisher process easier. Can we have that?

**Comment by pindec** [comment]
I agree that having these available to the process user on the command line would be helpful.

**Comment by robredpath** [comment]
@odscjames will outline the solution here - which may involve open-contracting/deploy#38

**Comment by odscjames** [comment]
> (on the command line ideally) 

I am taking this to mean (and have checked with @pindec ): not in a virtual environment :smile:

**Comment by odscjames** [comment]
Have now installed both Python packages outside the virtual environment to both users, analyse and process. 

After doc work in https://github.com/open-contracting/kingfisher/pull/330 I think this can be closed?

**Comment by duncandewhurst** [comment]
Great! Thank you @odscjames

**Comment by jpmckinney** [comment]
Doc work was done, so closing.
