### ISSUE TITLE
compile-releases: Crashes when OCID is none

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#204]
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
  File "ocdskingfisherprocess/cli/commands/transform_collections.py", line 41, in run_command
    transform.process()
  File "ocdskingfisherprocess/transform/compile_releases.py", line 24, in process
    self.process_ocid(ocid)
  File "ocdskingfisherprocess/transform/compile_releases.py", line 82, in process_ocid
    self.store.store_file_item(ocid+'.json', None, 'compiled_release', out, 1)
```

**Comment by odscjames** [comment]
Whichever idiot made this issue didn't note where the data was. Someone should look in the logs and pull that out, then we can decide how important it is to have a good solution to this.

**Comment by jpmckinney** [comment]
Don't be so hard on yourself :) I remember seeing this in Sentry: https://sentry.io/organizations/open-data-services/issues/1267063506/?project=1404981&query=is%3Aunresolved

Looks like `transform_collection` was 677.

**Comment by jpmckinney** [comment]
From https://crm.open-contracting.org/issues/4918#note-35, they have since corrected the issue. We might want to make this issue about adding a guard in case any future data has `ocid is None`, but it is low priority for now.

**Comment by jpmckinney** [comment]
This error keeps occurring and is now the most common error by far, so I'd increase it in priority.

`get_ocids` should perhaps not append an ocid if it is None, but it should at least warn if so.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Process: Don't compile release if ocid is None](https://trello.com/c/Ns1o2Vjx/138-process-dont-compile-release-if-ocid-is-none)

**Comment by jpmckinney** [comment]
Alternately, maybe the quickest solution is to just delete collection 677 so that we stop trying to compile its releases?

**Comment by jpmckinney** [comment]
With #249, ocid can't be null, but it can still be empty. This detail has been integrated into the new [technical proposal](https://docs.google.com/document/d/1pED3ujU3SGMvBu9RYyM5atY6cEE_cmPt7XqgekE2jYs/edit).
