### ISSUE TITLE
Data-Type - pass paths instead

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#209]
Basically to avoid the need to add a new data type when we come across something different from before in new API's.

https://github.com/open-contracting/kingfisher-scrape/issues/205#issuecomment-543832945

> Maybe instead of each time creating a new type like release_package_in_ocdsReleasePackage_in_list_in_results, the spider can instead pass a JSON path as a further parameter, indicating the root path of the packages? OCDS Kit has a --root-path option just for this. When processing an FTS file in OCDS Kit, I just set --root-path results.item.ocdsReleasePackage (using a syntax specific to ijson / yajl, but it's the same idea).

**Comment by jpmckinney** [comment]
This will be solved in Collect https://github.com/open-contracting/kingfisher-collect/issues/329, and the new load CLI command will take a `--root-path` argument. So, Process only needs to recognize basic OCDS formats.
