### ISSUE TITLE
Verbose Flag or Quiet Flag?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#21]
This has a Verbose flag, but we really don't use it. 

Comment from https://github.com/open-contracting/kingfisher/issues/255 : "Have seen a problem with user not understanding how to use tool, and if Verbose mode had been the default this would have been obvious to the user at the time. Consider switching defaults"

Remove verbose flag? Maybe add a quiet flag instead if we think that would be important.

For more debug level type messages, I'd lean toward using the normal Python Logging framework more.

**Comment by odscjames** [comment]
So unless others comment shortly, based on my experience with old tool I'm going to go with:

* remove verbose flag
* add a quiet flag
* get each of the CLI commands to print some more status as they run.

**Comment by jpmckinney** [comment]
Presumably closed by #73 and #79 and other referenced commits.
