### ISSUE TITLE
Increase test coverage in tests/test_transform_upgrade_1_0_to_1_1.py on the data and package_data table

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#214]
It came up recently that no tests failed when OCDS Kit was upgraded from 0.0.x to 0.1.x without making any changes to the code. 

Me and @rhiaro had already discussed how to tackle this; the tests tests/test_transform_upgrade_1_0_to_1_1.py should be extended to check the number of rows in the data and package_data table, and check the hash field of each row. 

This would have then failed during upgrading ocdskit , as the new data would not have been written to the data table.

The work in progress was stopped by #212, so made this issue to pick up again later.

**Comment by jpmckinney** [comment]
Please feel free to continue the WIP in a new branch – #212 was just to get work merged that seemed to have stalled in #194.

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Increase Kingfisher Process Test coverage for checks](https://trello.com/c/YKkoV0OG/163-increase-kingfisher-process-test-coverage-for-checks)
