### ISSUE TITLE
Add list-sources cli command

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#217]
This would make it easier for analysts use the same source_id when local loading updated versions of previously loaded data.

When local loading a file, first you must use the `new-collection` command which requires `sourceid` as a parameter.

Currently the only (?) way to get a list of source_ids is to query the `collection` table in the database.

Like the `list-collections` command it would be good to have a `list-sources` command, so the analyst can easily identify the source_id they have previously loaded data under.

Recently, this would have been useful for Paraguay and Portugal.

**Comment by jpmckinney** [comment]
I think this use case is fairly narrow. You can get the list like so:

curl -sS -n 'http://collect.kingfisher.open-contracting.org/listspiders.json?project=kingfisher' | python -m json.tool

I'll add this to the troubleshooting doc.

**Comment by jpmckinney** [comment]
Ah, nevermind, this is specifically to see the `*_local` source IDs.

**Comment by jpmckinney** [comment]
Similarly, this is a one-liner. Assuming you're already on the server since you're about to run local-load:

    psql ocdskingfisherprocess -c "SELECT source_id FROM collection GROUP BY source_id ORDER BY source_id"

If you just want source IDs containing "local":

    psql ocdskingfisherprocess -c "SELECT source_id FROM collection WHERE source_id LIKE '%local%' GROUP BY source_id ORDER BY source_id"
