### ISSUE TITLE
Delete collection (and all data) command

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#22]
Would be handy.

**Comment by jpmckinney** [comment]
See discussion in https://github.com/open-contracting/kingfisher/issues/106

**Comment by odscjames** [comment]
We will have a delete flag on collection table.

Background process - will go thru any delete flagged collections and actually remove data from database. Including data and package_data table.

**Comment by odscjames** [comment]
Shouldn't be allowed to delete data if transform is currently in operation - so need to look at that first!

**Comment by odscjames** [comment]
We can break this into multiple Pull Requests - this will help with small pull requests for less merge conflicts, and lets other things build on the delete functionality.

First pull request:
  *  Table collection has new column, deleted_at, a datetime like store_end_at, default is NULL. For this an alembic migration is needed  - see https://kingfisher-process.readthedocs.io/en/dev/development.html
  *  A new CLI command 'delete-collection', with a docs page.

This command should:

  *  Take in one ID of the collection (there is some library functions to make this easier, see https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/cli/commands/check_collection.py for an example)
 *  If is already marked as deleted, that's fine
 *  If any transforms of that have been started, don't let it be deleted - error!
 *  Mark as deleted in the database!

**Comment by odscjames** [comment]
Notes on code - thanks for taking the time to talk through it with me @BibianaC! 

In the CLI command, there’s no need to get the user to pass in date - we can just take the current date automatically. datetime.datetime.utcnow()

Also we can use the library function configure_subparser_for_selecting_existing_collection() and run_command_for_selecting_existing_collection () that the existing check-collection command uses here.

Also, this needs to actually call something on the database class to write to the database - just setting the date in memory doesn't automatically save to the database. This will need to be a new method on the database class. example https://github.com/open-contracting/kingfisher-process/blob/80-end-transform/ocdskingfisherprocess/database.py#L417

Also, The transform check needs to be a bit different. The check currently sees if the collection the user wants to delete was a transform. We actually need to check if any transforms have been created from the collection they want to delete.

id | source | transform_from_collection_id
1    source  NULL
2    destination 1

So if the user wants to delete collection 1, we need to do: SELECT * FROM collection WHERE transform_from_collection_id = 1 and then see if any rows are returned or not - this should be a new function on the database class. eg like is_record_check_done

The migration needs to create and drop the column. eg 77ac9e65197e_checks

Docs page should be linked from the docs index page so it appears in the menu. If you look at docs/cli.rst it's a simple add to the toc

**Comment by odscjames** [comment]
That pull request is done - thank you! Notes from call:

Next bit is, write SQL queries that will actually delete data from database.

So if we know a collection of id COLLECTION_ID is flagged for deletion, we need SQL queries to delete from:

* collection_file
   DELETE FROM collection_file WHERE collection_id=COLLECTION_ID
* collection_file_item
   DELETE FROM collection_file_item
   JOIN collection_file ON collection_file.id = collection_file_item.collection_file_id
   WHERE collection_file.collection_id=COLLECTION_ID
* release
* record
* release_check
* record_check
* release_check_error
* record_check_error

And it must be deleted from the bottom of the list first

(I haven't tested the SQL above, I just wrote during call - do test it!)

**Comment by jpmckinney** [comment]
Going back to discussion in open-contracting/kingfisher#106, wouldn't it be better to use cascades for (1) less SQL statements therefore less opportunity for error and (2) more future-proof, given that if we add more tables that foreign-key onto these tables, we don't have to remember to update this command's code?

**Comment by robredpath** [comment]
@jpmckinney there's definitely the potential to refactor to using cascades in the future; it certainly feels like a more elegant solution overall. However, we're slightly worried about the risk of cascades being a bit *too* effective, especially with the de-duping mechanism we're using on the data table. I've opened #96 to continue that discussion. Please do contribute there if I've missed any salient points from my brief summary. 

For now, we're going with specific table deletions so as to err on the side of safety - especially as we're coming up to the end of the first of the two sprints we've got on this, and there's plenty else to be getting on with.

**Comment by odscjames** [comment]
Closing now - work can continue in individual issues for small details.
