### ISSUE TITLE
Database tables are config-independent and should not be under DataBase class

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#231]
The tables should always have the same schema… We have no use case for connecting to multiple databases whose tables have config-based schemas, so this is just extra complexity.

**Comment by jpmckinney** [comment]
Attaching a patch to make the change. I thought I needed this change to be able to more easily run the tests using transactions and rollbacks (instead of deleting and re-creating tables, which is slow), but I think I can just patch the `get_engine()` function.

[move-tables-out-of-class.txt](https://github.com/open-contracting/kingfisher-process/files/3953291/move-tables-out-of-class.txt)

**Comment by jpmckinney** [comment]
Is there a reason the DB session isn't established just once, like in Django and [Flask-SQLAlchemy](https://github.com/pallets/flask-sqlalchemy/blob/2.4.1/flask_sqlalchemy/__init__.py#L715) apps? Doing so would reduce complexity and make development and testing easier.

**Comment by odscjames** [comment]
> Database tables are config-independent and should not be under DataBase class
> The tables should always have the same schema… We have no use case for connecting to multiple databases whose tables have config-based schemas, so this is just extra complexity.

They do always have the same schema - while technically putting them under DataBase class allows different ones, there was never any intention to do that and that's just how the code worked out. Moving them to the module seems fine to me.

> Is there a reason the DB session isn't established just once

I think it is - the 2 entry points for the app are CLI and Web, and in each case it's created once and then passed round? https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisher-process-cli#L23 and https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/web/app.py#L34

**Comment by jpmckinney** [comment]
Okay, so there can be a bit of cleanup to remove the current ambiguity about intentions.

The DB session is re-established each time get_engine().begin() is called. (More specifically, Engine.begin() calls [Engine.connect()](https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.Engine.connect), which takes a connection from a connection pool and then returns it at the end of the context manager.)
