### ISSUE TITLE
Add collection_id to release, record, compiled_release (instead of using views)

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#236]
Since we only insert and don't update most tables, we won't have the usual downsides to denormalization.

The new collection_id column should have an index. Note the performance of the views (without an index):

```sql
EXPLAIN ANALYZE SELECT * FROM release_with_collection WHERE collection_id = 800;
```

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Gather  (cost=1613330.92..4072300.22 rows=25972 width=69) (actual time=8.118..12.213 rows=0 loops=1)
   Workers Planned: 4
   Workers Launched: 4
   ->  Parallel Hash Join  (cost=1612330.92..4068703.02 rows=6493 width=69) (actual time=0.230..0.231 rows=0 loops=5)
         Hash Cond: (release.collection_file_item_id = collection_file_item.id)
         ->  Parallel Seq Scan on release  (cost=0.00..2317749.09 rows=36961809 width=65) (never executed)
         ->  Parallel Hash  (cost=1612272.79..1612272.79 rows=4650 width=8) (actual time=0.030..0.030 rows=0 loops=5)
               Buckets: 32768  Batches: 1  Memory Usage: 0kB
               ->  Parallel Hash Join  (cost=39248.79..1612272.79 rows=4650 width=8) (actual time=0.063..0.065 rows=0 loops=1)
                     Hash Cond: (collection_file_item.collection_file_id = collection_file.id)
                     ->  Parallel Seq Scan on collection_file_item  (cost=0.00..1503531.88 rows=26473188 width=8) (never executed)
                     ->  Parallel Hash  (cost=39170.17..39170.17 rows=6290 width=8) (actual time=0.014..0.015 rows=0 loops=1)
                           Buckets: 16384  Batches: 1  Memory Usage: 0kB
                           ->  Parallel Index Scan using unique_collection_file_identifiers on collection_file  (cost=0.69..39170.17 rows=6290 width=8) (actual time=0.014..0.014 rows=0 loops=1)
                                 Index Cond: (collection_id = 800)
 Planning Time: 0.428 ms
 Execution Time: 12.254 ms
```

Compare that to a table using an index:

```sql
EXPLAIN ANALYZE SELECT * FROM release WHERE collection_file_item_id = 106127340;
```

```
                                                                     QUERY PLAN                                                                     
----------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using release_collection_file_item_id_idx on release  (cost=0.57..1431.45 rows=3339 width=65) (actual time=0.017..0.017 rows=0 loops=1)
   Index Cond: (collection_file_item_id = 106127340)
 Planning Time: 0.067 ms
 Execution Time: 0.028 ms
```

For backwards-compatibility with existing notebooks, I propose moving the one-time creation of the old views to kingfisher-views (though keeping them in the `public` schema).

**Comment by romifz** [comment]
Sounds good for me!

**Comment by duncandewhurst** [comment]
Makes sense to me too

**Comment by odscjames** [comment]
I'm not sure that comparison is a fair one; views can use index's too so if we are seeing Seq Scans (as we are) it may be that adding indexes speeds up the view read.

Tho in this case, given the lack of updates to this data, denormalization is probably fine.

>  I propose moving the one-time creation of the old views to kingfisher-views (though keeping them in the public schema).

I would keep them in Process; then developers working on changing Process are aware that any changes they make to the database structure might mean a change to these legacy views is needed, and such a change can be enforced in 1 pull request. If code for something is split into 2 repos, it's easy to miss when working on it and harder to coordinate changes to it.

**Comment by jpmckinney** [comment]
Moving discussion of where the views ought to live to https://github.com/open-contracting/kingfisher-views/issues/62

**Comment by odscjames** [comment]
I still think that dealing with the soon-to-be deprecated "*_with_collection" views should happen in the Process app - I'll comment on https://github.com/open-contracting/kingfisher-views/issues/62 with more.

**Comment by odscjames** [comment]
Reopening as deploy failed

**Comment by odscjames** [comment]
We will deploy a different way.

Briefly, the procedure is to make sure the code can work with the new and old database structures, and then do the long-running database migration in the background while others work, then remove that special code.

1) Deploy adding columns, NULLABLE, and indexes
2) Deploy changes to Store so any new data written fills this column.
3) Manually run SQL to fill existing rows with data.
4) Deploy changes to make it NOT NULL.
5) Finally, deploy changes to read from the table and not the now-deprecated view.

This will require no downtime notices and no special downtime (beyond the usual "make sure no spiders are running when you deploy")

**Comment by odscjames** [comment]
Stage 1 Deployed

**Comment by odscjames** [comment]
Stage 2 Deployed

**Comment by odscjames** [comment]
Stage 3 will be done in a TMUX session called databasemigration under the user ocdskfp.

**Comment by odscjames** [comment]
Records done. Servers might be rebooted this afternoon, will start next one after reboot.

**Comment by jpmckinney** [comment]
For the remaining tables, I think we should drop the index, then update, then `CREATE INDEX CONCURRENTLY`. Creating an index after a bulk operation is faster. Without the `CONCURRENTLY` keyword, `CREATE INDEX` will block INSERTs.

I think the UPDATE only locks rows, which blocks other UPDATEs to the same rows (which we don’t perform), but doesn’t block SELECT or INSERT. We could still update in batches though if we wanted to be conservative.

**Comment by odscjames** [comment]
True, but it's more complex for staff and the total time may be the same anyway. Given this is a one time operation and no down time is required, I'm not sure it's worth putting too much billable time into working out which is best. Especially as ... 

> We could still update in batches though if we wanted to be conservative.

.... I have a horrible feeling we will end up here anyway.

I'll start "compiled_release" now (It's smaller than "release"), will leave it all weekend when the server is quiet and check in first thing Monday morning.

**Comment by jpmckinney** [comment]
Sounds good. The alternative commands would be:

```sql
DROP INDEX release_collection_id_idx;

UPDATE release SET collection_id = release_with_collection.collection_id
FROM release_with_collection WHERE release.id = release_with_collection.id");

CREATE INDEX CONCURRENTLY release_collection_id_idx ON public.release USING btree (collection_id);
```

The last statement was collected by running `pg_dump -COsxn public ocdskingfisherprocess | grep " release_collection_id_idx"`.

**Comment by jpmckinney** [comment]
`compiled_release` completed. I'm going to run the above command in the same tmux session.

**Comment by odscjames** [comment]
I started CREATE INDEX and will do a pull request for stage 4 now

**Comment by odscjames** [comment]
Stage 4 Deployed

**Comment by odscjames** [comment]
Stage 5 Depolyed

**Comment by odscjames** [comment]
I will leave this open for a day or two to make sure no errors arise, then will open a CRM ticket to alert all analysts to this new feature, and tackle #256. Then I think we can close this.

**Comment by odscjames** [comment]
CRM ticket, 2 pull requests awaiting review, this is almost ready to be closed
