### ISSUE TITLE
Add indices to all foreign keys

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#237]
Not all foreign keys have indexes (SQLAlchemy doesn’t add them but default).

If necessary, we can [build indexes concurrently](https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-CONCURRENTLY).

The new indices would correspond to (replacing `<name>`):

        CREATE INDEX <name> ON public.collection USING btree (transform_from_collection_id);
        CREATE INDEX <name> ON public.collection_file USING btree (collection_id);
        CREATE INDEX <name> ON public.collection_file_item USING btree (collection_file_id);
        CREATE INDEX <name> ON public.collection_note USING btree (collection_id);
        CREATE INDEX <name> ON public.record USING btree (package_data_id);
        CREATE INDEX <name> ON public.record_check USING btree (record_id);
        CREATE INDEX <name> ON public.record_check_error USING btree (record_id);
        CREATE INDEX <name> ON public.release USING btree (package_data_id);
        CREATE INDEX <name> ON public.release_check USING btree (release_id);
        CREATE INDEX <name> ON public.release_check_error USING btree (release_id);

**Comment by odscjames** [comment]
That seems sensible. We could be paranoid and check whether any of these will create a lot of turn over on data writes, but it's probably ok.
