### ISSUE TITLE
Document use of en_GB.UTF-8 database collation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#239]
OCP standardizes on American English (i.e. en_US.UTF-8).

I don't know that there's any real difference, but if there's a reason, it'd be good to document it.

I think the only way to change the default collation is by re-creating the DB (not worth it).

**Comment by odscjames** [comment]
I think this was just done as a default value.

I have not come across and I don't think there is any difference between the two that matters to us, given that we don't do the kind of free-text operations where differences would surface.

**Comment by jpmckinney** [comment]
Done in edc685919baa658aa69ecec8f6e4536cfb0d116a
