### ISSUE TITLE
Add config field to collection, instead of a growing list of fields

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#240]
We presently have `check_data` and `check_older_data_with_schema_version_1_1`, to configure how checks are performed. I anticipate the list of possible configurations to grow over time.

I think it'd be better to have a JSONB `configuration` field on `collection` instead of growing list of fields (`check_older_data_with_schema_version_1_2`, etc.). The field would store a JSON object.

**Comment by odscjames** [comment]
> I anticipate the list of possible configurations to grow over time.

What growth do you anticipate? So far the only growth we will have is every time a non-patch version of the standard is released, so not much :-)

> I think it'd be better to have a JSONB configuration field on collection instead of growing list of fields

We could do.  My personal preference is if we only have a few options to have fields - then your essentially enforcing that there are values for each collection in way that's harder to do with a JSON field. Also it's clearer when looking at the database schema what to expect.

**Comment by jpmckinney** [comment]
Some possibilities:

* [Configure the ocsdmerge behavior](https://github.com/open-contracting/ocds-merge#working-with-degenerate-data), when initializing the collection for the compile-releases transform
* Indicate whether to stop on an error (useful if figuring out how to handle a new error caused by a specific collection), or to try to transform as much of a collection as possible

If we add new transforms, they might come with their own configurations. There was discussion at some point to add a method (likely to OCDS Kit first) to fix some easy OCDS errors (e.g. convert strings to numbers on numeric fields, if the string can be parsed as such; convert numbers to strings for string fields; normalize all `id` fields to strings). An analyst might want to opt-in to each of these options, which might grow within OCDS Kit, and we wouldn't want to have to alter the KF tables every time there's an OCDS Kit upgrade.

**Comment by odscjames** [comment]
Sounds like some more spec work around transforms is needed before this is firmed up, but I'd note we can mix fields and JSON columns, and this might be the best of both, eg:
  * check_data BOOLEAN
  * check_older_data_with_schema_version_1_1 BOOLEAN
  * merge_options JSONB
  * etc

**Comment by jpmckinney** [comment]
`check_older_data_with_schema_version_1_1` is a configuration relevant to libcoveocds (for which we could potentially make other options available, if there is demand).

So, one design would have a new field for each new operation:

* check_options (libcoveocds)
* compile_options (ocdsmerge)
* upgrade_options (ocdskit)

Whenever we would add a new operation, we would add a new field.

However, while I generally like explicit fields (for greater consistency across collections and for easy querying), in this case, it seems like overhead to have to alter the collection table whenever we add a new transform. I also don't know a use case for querying against these options; I think they are only relevant when processing a given collection.

So, an `options` field seems fine to me. In terms of promoting consistency, the `Collection` model can offer functions for setting the options, so that it's solely responsible for the structure of the options field, e.g. `collection.set_check_options(check_older_data_with_schema_version_1_1=None)` results in `{"check_options": {"check_older_data_with_schema_version_1_1": true}`.

`check_data` is different, as it's more about the steps of the pipeline. Whereas the intention to upgrade and compile can be indicated by the presence of a transform collection, we can't similarly indicate the intention to check, and so we need something on the collection table. For now, we can just leave that boolean, as we don't have any other operations that don't result in new collections.
