### ISSUE TITLE
Is there a use case for deleting a source collection, but keeping its transforms?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#243]
Following from https://github.com/open-contracting/kingfisher-process/issues/141#issuecomment-517288985

Having the concept of a 'deleted collection' adds complexity, because many queries, commands, operations, etc. will have to be aware of the concept (mainly to exclude deleted collections from consideration), including queries run by helpdesk analysts.

(*Update for clarification:* We need the concept of a 'collection marked for deletion', because deleting a collection can take some time. However, once the collection is indeed deleted, should we delete the row from the `collection` table as well?)

The only good reason I can think of to not just delete collections from the database entirely is if it's a source collection with (non-deleted) transformed collections. In such a case, it's useful to keep the notes, errors and warnings from the source collection, to understand the transformed collections' provenance.

However, **is there ever a case where we want to delete the source collection, but keep the transforms?** I can see there could be a niche use case to save disk space eventually, but I think we can consider other alternatives that don't add as much complexity.

**Comment by romifz** [comment]
> However, **is there ever a case where we want to delete the source collection, but keep the transforms?**

None I can think of.

**Comment by jpmckinney** [comment]
We have a few cases where a source collection is deleted, but not its transform:

```sql
SELECT s.source_id, s.id, d.id, s.transform_type, d.transform_type
FROM collection d
INNER JOIN collection s ON
    d.transform_from_collection_id = s.id
WHERE
    d.deleted_at IS NULL AND
    s.deleted_at IS NOT NULL;
```

```
    source_id     | id  | id  | transform_type |   transform_type   
------------------+-----+-----+----------------+--------------------
 digiwhist_france | 106 | 107 |                | upgrade-1-0-to-1-1
 digiwhist_france | 118 | 119 |                | upgrade-1-0-to-1-1
 digiwhist_france | 124 | 125 |                | upgrade-1-0-to-1-1
 digiwhist_france | 127 | 128 |                | upgrade-1-0-to-1-1
 digiwhist_france | 130 | 131 |                | upgrade-1-0-to-1-1
 digiwhist_france | 133 | 134 |                | upgrade-1-0-to-1-1
```

We have collections 136 (source), 137 (upgrade), 138 (compile) for digiwhist_france, so I don't think we need to hold onto the above and can just delete them.

I think the above were just forgotten when the analyst deleted the source collections.

**Comment by yolile** [comment]
> However, is there ever a case where we want to delete the source collection, but keep the transforms?

No, only, as you said, when you want to save some space and you need to work only with, for example, the compiled releases.

**Comment by odscjames** [comment]
Even if we delete rows from the collection table directly, we still need the concept of deleted collections.

This is because it's not possible to instantly delete a collection and all it's data, so we need a way to mark a collection as deleted and then allow it do be deleted. In the mean time, we need to make sure other operations don't try and work with this collection.

CASCADE deletes won't instantly delete a collection, as they don't account for the data and package_data tables. And if we want deletes to smartly work into the views component to, CASCADES won't work. (Currently things in process and views must be deleted separately :-/ ). Even if they did, we have never tried running a CASCADE delete on a giant GB-size collection - we may find the resulting transaction locks up the table for a long period of time.

**Comment by jpmckinney** [comment]
This issue isn't about cascades. It's about whether – once data, package_data, etc. are all deleted – we can delete the collection itself. The current code doesn't do that. It keeps the collections forever.

**Comment by duncandewhurst** [comment]
> However, is there ever a case where we want to delete the source collection, but keep the transforms?

Not that I can think of.

Though, in practice, I haven't actually marked any collections for deletion.

**Comment by pindec** [comment]
> However, **is there ever a case where we want to delete the source collection, but keep the transforms?**

The only reason I can think of would be to save disk space.

It's likely that the spare collections sitting around are due to not remembering to mark all transforms for deletion.
