### ISSUE TITLE
Add mechanism for allowing multiple of the same transform per collection

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#251]
Follow-up to #235

Presently, at the application level, we require transformed collections to be unique (i.e. one 'compile-releases' collection per collection). We can discuss under what conditions (and using what process) analysts should be able to create multiples of the same transform of a given collection.

**Comment by jpmckinney** [comment]
Some ideas. We can:

* Make adding a collection note mandatory
* Recommend that the user delete the other transforms if they are unwanted

**Comment by romifz** [comment]
I'm stuck at the moment with a transformed collection that can't finish running (it started but didn't finish, don't know the reason, running `transform-collection` raises an exception), but I can't create another one neither because even if I mark it as deleted `new-transform-compile-releases` says there is an existing collection. From #142 I understand that this may not be complex to implement, but it would be useful if we can find a way!

**Comment by jpmckinney** [comment]
If #253 is merged, you can recreate the collection after the old one is deleted.

What is the collection ID and full exception with backtrace?

**Comment by odscjames** [comment]
@romifz Was it "DatabaseStore class tried to insert a duplicate collection_file_item row!"? Collection ID's would help thought.

**Comment by romifz** [comment]
> @romifz Was it "DatabaseStore class tried to insert a duplicate collection_file_item row!"? Collection ID's would help thought.

Yes, that was it. I marked the collection for deletion though and it seems to be deleted now. What I did:

* I ran the honduras_oncae scraper.
* Original collection (850) finished without issues, but its transformations didn't finish for some unknown reason (I checked after a few days). Both had partial data.
* I ran `transform-collection` over the upgrade-to-1.1 collection (851), and it finished without issues.
* I ran `transform-collection` over the compiled releases collection, and I got the error you mention.

**Comment by odscjames** [comment]
Ah, I see. This error can happen with the "compile releases" transform if 2 processes try and transform the same bit of data at once. It's safe to just re-run transform-collection later on the offending collection if this happens; A) this crash does not leave any bad state in the database B)  transform-collection is designed to be an idempotent operation if called on collections that are already transformed (in whole or in part). We could look at this situation further (make crash message clearer as a first step), but there may be no point if process is all about to change anyway.

In terms of the original topic of this ticket, this is interesting to explore; it may be that there is no valid use case for "analysts should be able to create multiples of the same transform of a given collection" other than recovering from problems, in which case maybe we should invest time in fixing problems instead :-)

**Comment by jpmckinney** [comment]
Closing as no use cases have emerged besides re-running a transform - which can be done by deleting the original transform.
