### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#267]
Seeing in logs:

```
  File "./ocdskingfisherprocess/web/views_api_v1.py", line 121, in dispatch_request
    request.form.get('local_file_name')
  File "./ocdskingfisherprocess/store.py", line 95, in store_file_from_local
    self.store_file_from_data(filename, url, data_type, data, file_warnings=file_to_store.get_warnings())
  File "./ocdskingfisherprocess/store.py", line 106, in store_file_from_data
    objects_list.extend(data)
TypeError: 'NoneType' object is not iterable
```

@romifz Can you supply more details on which scraper it was?

**Comment by odscjames** [comment]
" the honduras_portal_releases and honduras_portal_records scrapers"

**Comment by odscjames** [comment]
Think the end points may have changed?

This is meant to be record_list and release_list but if I look I see a data object with "recordPackage" and "releasePackage" keys.

**Comment by romifz** [comment]
Thanks James, I'm opening another issue in kingfisher-scrape to update the scrapers.
