### ISSUE TITLE
Allow analysts to see logs

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#277]
* https://github.com/open-contracting/kingfisher-scrape/issues/334
* https://github.com/open-contracting/kingfisher-process/issues/267
* https://github.com/open-contracting/kingfisher-scrape/pull/339

This issue of changing endpoints was dealt with fine but one user had to make requests to a sever admin to look in Logs to see the exact error.

Can we make the logs more available to users on that server?

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Allow analysts to see logs](https://trello.com/c/Tr4N2QEE/197-allow-analysts-to-see-logs)

**Comment by jpmckinney** [comment]
I upgraded OCP's (unused) Sentry account (`open-contracting-partnership`) to Team. Can you transfer all projects to that account? There's an option on the settings page. (This is something we want to do independent of this issue.)

I can then give access to all analysts as a first step, with respect to this issue.

**Comment by odscjames** [comment]
Have committed to salt and edited on server /etc/logrotate.d/kingfisher.conf - now leave for a week and make sure this works

**Comment by odscjames** [comment]
Log world readable this morning, seems grand. Just need to doc.

**Comment by odscjames** [comment]
Think this is now closable.
