### ISSUE TITLE
Compile Release Transform: raise MissingDateKeyError('The `date` field of at least one release is missing.')

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#279]
We should at least make sure such errors don't crash the whole Python process - but how should the app handle data with no date?

**Comment by jpmckinney** [comment]
What do you think the behavior should be, @yolile @romifz @mrshll1001?

The problem is that, if the date is missing, then the release can't be ordered correctly for the merge routine.

**Comment by romifz** [comment]
I think these releases could be ignored. Are transformation warnings reported somewhere? It would be nice to have a place to look for these.

**Comment by jpmckinney** [comment]
For your question, that's the subject of #242

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compile Release Transform: date missing](https://trello.com/c/sRtiAXxV/205-compile-release-transform-date-missing)

**Comment by odscjames** [comment]
As this is causing crashes, I'm going to do a quick fix under the small work rule. I'll just get it to drop whole OCID's if "date" is missing with a note. This is a bit of an extreme option but at least it won't be crashing and other data will be processed.

**Comment by odscjames** [comment]
Deployed quick fix. Leaving open to work out if better way to process?

**Comment by jpmckinney** [comment]
@romifz Does it make sense to not produce any compiled release for an OCID, if any of its individual releases lacks a date? Or is it preferable to create a compiled release with the individuals releases that have a date? I don't have a strong opinion; it's a choice between missing processes and missing releases.

cc @duncandewhurst as not tagged earlier due to leave.

**Comment by romifz** [comment]
I think the second option may be better. When doing a review we want to have as many data available as possible. If we exclude processes there is a small chance of missing an issue we can report on.

**Comment by duncandewhurst** [comment]
> I think the second option may be better. When doing a review we want to have as many data available as possible. If we exclude processes there is a small chance of missing an issue we can report on.

Agreed. We should also add a step to our standard notebook set up to check for these errors. I've added a note to crm issue #3918

**Comment by odscjames** [comment]
Looking at this. Still good to do quick fix tho, as that will catch any errors OCDS Merge throws, not just date ones.

**Comment by odscjames** [comment]
Deployed new process - will merge with date ones and alert. Think this is now done.
