### ISSUE TITLE
Compile Releases Transform may end up trying duplicate work

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#283]
It makes a list of OCID's it needs to compile by crossing data in the source destination with data in destination one and looking for OCID's not processed yet.

We recently added something so that if an OCID can't be processed for whatever reason, it adds a collection note and moves on. #63 #279

But this means it may try and do work twice
* Start collection 1
* Make list of OCID's not yet processed
* Try and process OCID 1 and fail, log collection note
* Process ends before collection marked as finished
* Start process again
* Start collection 1
* Make list of OCID's not yet processed
* Try and process OCID 1 and fail, log collection note

We are saved a bit in that database.add_collection_note will not insert duplicate notes, so we don't end up with a lot of database entries. But we do waste machine time trying something we've already tried.

**Comment by jpmckinney** [comment]
This problem will go away once we use queues, so I'm okay with closing this issue as the duplicate work has no ill effect besides being a tiny bit slower.

**Comment by jpmckinney** [comment]
See also discussion in https://github.com/open-contracting/kingfisher-process/pull/244
