### ISSUE TITLE
Update _delete_orphan_data_package_data to delete in blocks

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#299]
The current query has now been running for 18 days… (I stopped the deletion cron job to not start a new query once a week.)

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update _delete_orphan_data_package_data to delete in blocks](https://trello.com/c/YMFuBDoo/229-update-deleteorphandatapackagedata-to-delete-in-blocks)

**Comment by odscjames** [comment]
Now live and deleted 2M records over this weekend
