### ISSUE TITLE
CoVE sentry errors in kingfisher process

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#301]
CoVE fails when a definition in an extension cannot be dereferenced (see https://github.com/OpenDataServices/cove/issues/1286). This means the CoVE checks don't run, so from an analyst's perspective, it looks like there are no issues with the data.

According to CRM issue [#6128#note-21](https://crm.open-contracting.org/issues/6128#note-21) Sentry reports the error.

Can this type of error be captured in kingfisher-process? Or can some documentation be authored to explain how analysts should check for this type of error?

**Comment by duncandewhurst** [comment]
Another example of a similar issue which causes to CoVE to fail: https://github.com/OpenDataServices/cove/issues/1287

I'm not sure how this one is reported in Sentry.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate CoVE errors in Kingfisher Process Sentry](https://trello.com/c/gyTXFIUt/232-investigate-cove-errors-in-kingfisher-process-sentry)

**Comment by Bjwebb** [comment]
Links to Sentry issues:
Dereferencing (RefResolutionError): [KINGFISHER-PROCESS-6D](https://sentry.io/organizations/open-contracting-partnership/issues/1740268826/?referrer=github_integration)
Null in parties array (TypeError argument of type 'NoneType' is not iterable): [KINGFISHER-PROCESS-6E](https://sentry.io/organizations/open-contracting-partnership/issues/1752169577/?referrer=github_integration)

**Comment by odscjames** [comment]
We already have 2 tables in the database, record_check_error and release_check_error.

However, entries are only written to these if lib-cove crashes with an special APIException error. https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/checks.py#L188

It seems like this is a 2 parter here: 
* change _check_release_row and _check_record_row to catch any Pthon Exception
* make sure record_check_error and release_check_error are documented somewhere for analysts properly.

**Comment by jpmckinney** [comment]
If we're going to edit that code, we might want to do #242 at the same time.

**Comment by odscjames** [comment]
Live and seen working, analysts told of new docs page
