### ISSUE TITLE
Some warnings columns have the string "null" in them

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#306]
An actual NULL would be better

Found while doing https://github.com/open-contracting/kingfisher-process/pull/305

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Some warnings columns have the string "null" in them](https://trello.com/c/KEV2yh0B/264-some-warnings-columns-have-the-string-null-in-them)

**Comment by odscjames** [comment]
Slight correction on looking into this, it wasn't saving as string, it was saving as a JSON representation of Null.

However, if we take the use case as "Analysts want to search for errors/warnings easily without considering weird edge cases like that", still seems worth fixing. 

And fortunately, this is a edge case SQLAlchemy already cover in an easy option.

**Comment by jpmckinney** [comment]
Note to self that Django uses SQL NULL by default, instead of JSON null for JSONField's.
