### ISSUE TITLE
Where we repeat the same SELECT call with LIMIT to get work to do, look at  server-side cursor instead

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#307]
From https://github.com/open-contracting/kingfisher-process/pull/304

Places this happens:

* database.py, _delete_orphan_data_data
* database.py,_delete_collection_run_sql_in_blocks
* probably database.py, _delete_orphan_data_package_data after https://github.com/open-contracting/kingfisher-process/pull/304 merged

**Comment by jpmckinney** [comment]
We get this for free in Django if `QuerySet.iterator()` is used, so closing. https://docs.djangoproject.com/en/3.1/ref/databases/#server-side-cursors
