### ISSUE TITLE
json 2 standard .sql files

### ISSUE THREAD

**Issue by vlasvlasvlas** [open-contracting/kingfisher-process#314]
Hi! i was looking for a tools that let me convert the json to standard .sql files, i'm trying to import a release package into sql server using this structure https://kingfisher-views.readthedocs.io/en/latest/database.html , and wondering if there is a tool that's already inside kingfisher that may help me in this job.

is there a tool available that may help me with this data import 2 sql server using kingfisher database structure?

thanks!
love the project!

**Comment by vlasvlasvlas** [comment]
i am aware of this .sql files: https://github.com/open-contracting/kingfisher-views/tree/master/sql

but they are prepared to get data from a json / jsonb postgresql data type,i was wondering if there area any openjson() sql server files

**Comment by jpmckinney** [comment]
Closing in favor of https://github.com/open-contracting/kingfisher-views/issues/136
