### ISSUE TITLE
Django branch testing with Pelican

### ISSUE THREAD

**Issue by jakubkrafka** [open-contracting/kingfisher-process#331]
| Source                                 | KC NG -> KP NG         | Pelican NG          | Pelican old                  | Checked            |
| ---                                        | ---                                | ---                        | ---                                | ---                |
| canada_buyandsell             | :construction:            |                              |  :white_check_mark:  | :heavy_minus_sign: |
| canada_montreal                | :construction:            |  :wavy_dash:       |  :wavy_dash:                | :heavy_minus_sign: |
| nepal_portal                        | :construction:            |  :wavy_dash:       |   :wavy_dash:              | :heavy_minus_sign: |
| zambia                                 | :construction:            |                              |    :white_check_mark:  | :heavy_minus_sign: |
| uk_contracts_finder           | :construction:             |                               |  :white_check_mark:  | :heavy_minus_sign: |
| afghanistan_records          | :construction:            |                               |  :white_check_mark:  | :heavy_minus_sign: |
| paraguay_dncp_records    |  :construction:                      |                               |   :construction:          | :heavy_minus_sign: |
| honduras_portal_records  | :construction:            |                               |    :wavy_dash:            | :heavy_minus_sign: |
| digiwhist_croatia                |  :construction:            |                               |    :wavy_dash:            | :heavy_minus_sign: |
| nigeria_budeshi_records   | :construction:            |                              |  :white_check_mark:  | :heavy_minus_sign: |
| uruguay_records                |   :construction:           |                              |    :wavy_dash:            | :heavy_minus_sign: |
| uruguay_releases               |    :construction:          |                              |  :white_check_mark:  | :heavy_minus_sign::construction

### Legend
:white_check_mark: - done
:construction: - in progress
:wavy_dash: - not available

**Comment by jpmckinney** [comment]
* uruguay_records has only linked releases
* uruguay_releases has many releases per OCID

**Comment by jakubkrafka** [comment]
Perf notes:
```
scrapy crawl digiwhist_croatia 2>   132.27s user 10.28s system 99% cpu 2:22.88 total
scrapy crawl digiwhist_croatia 2>   2512.95s user 107.90s system 35% cpu 2:04:03.48 total
```

**Comment by jpmckinney** [comment]
@jakubkrafka What's the significance of the perf notes?

**Comment by jakubkrafka** [comment]
Closed as the big testing happened in the scope of data registry.
