### ISSUE TITLE
Bad increase of sequence number for collection id

### ISSUE THREAD

**Issue by nativaldezt** [open-contracting/kingfisher-process#332]
The last collection id is very far from the previous one.
![image](https://user-images.githubusercontent.com/72802235/111462270-00035b80-86fd-11eb-99b5-c9e273b9bb7a.png)

**Comment by jpmckinney** [comment]
Fixed in https://github.com/open-contracting/kingfisher-process/commit/55f2cab04614eeae9b6ecb2f8595921c27387e15
