### ISSUE TITLE
Use OCDS Kit, not OCDS Merge directly, for merging

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#334]
As specified in the doc: https://docs.google.com/document/d/1pED3ujU3SGMvBu9RYyM5atY6cEE_cmPt7XqgekE2jYs/edit#heading=h.35zv86q5fqzk

> Reads a message from the “compile-releases” queue, processes the data **using OCDS Kit’s merge function**, and stores the results in the transformed collection. *(emphasis added)*

Using OCDS Merge directly means extensions are not considered, which produces incorrect results.

Background: https://github.com/open-contracting/kingfisher-process/issues/11#issuecomment-614855920

Related: #122

**Comment by jakubkrafka** [comment]
Implemented.

**Comment by jpmckinney** [comment]
@jakubkrafka Is it possible to pass the package data to the merge function (e.g. pass packaged data instead of individual releases)? Otherwise extensions will still not be considered.

**Comment by jakubkrafka** [comment]
Implemented and tested - looks fine to me right now.

**Comment by jpmckinney** [comment]
Noting that we agreed to switch back to OCDS Merge, but to use ProfileBuilder to create the schema.
