### ISSUE TITLE
Upgrade to Django 3.2 LTS

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#335]
OCP prefers LTS releases.

**Comment by jpmckinney** [comment]
Blocked by #336 

To upgrade:

* Relax Django version constraint in requirements.in
* Run pip-compile -P django; pip-compile requirements_dev.in
* `django.contrib.postgres.fields.JSONField` is deprecated. Remove the import from `models.py` and use `models.JSONField` instead. Then, run the `makemigrations` command.
* We can update links in comments from `/2.2/` to `/3.2/`

**Comment by jakubkrafka** [comment]
Done.
