### ISSUE TITLE
Consider alternative to Django Tastypie

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#336]
Django Tastypie isn't being kept up-to-date with Django. (No commits since 15 months ago for Django 3.0). https://github.com/django-tastypie/django-tastypie

I created a PR to see if django-tastypie's tests pass against newer versions of Django. Some tests fail: https://github.com/django-tastypie/django-tastypie/pull/1623

Would Django REST Framework be an option?

**Comment by jpmckinney** [comment]
As an update, I give up trying to get Tastypie tests to pass.

**Comment by jakubkrafka** [comment]
Tastypie killed, will be replaced by Django rest if needed.
