### ISSUE TITLE
If Kingfisher Collect yields no data or invalid JSON, Process should still complete

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#354]
Related: https://github.com/open-contracting/data-registry/issues/190

**Comment by yolile** [comment]
And also if there are some JSON with errors from collect, related: https://github.com/open-contracting/kingfisher-collect/issues/897

**Comment by jpmckinney** [comment]
> And also if there are some JSON with errors from collect, related: https://github.com/open-contracting/kingfisher-collect/issues/897

Right now, a collection is not marked completed in this scenario, because there will be leftover LOAD steps.

Currently, `file_worker` will still delete a LOAD step if the error raised is due to a duplicate message (e.g. already exists, integrity error). We *could* change this to also delete the step for the other exceptions that we handle in this worker (incomplete JSON, etc.) – we'd pass these additional exceptions as a tuple to the `delete_step` context manager.

**Comment by jpmckinney** [comment]
Based on how we implemented `ValidateJSONMiddleware` in Kingfisher Collect, spiders can opt-in to JSON validation, in which case invalid JSON gets excluded on Collect's end, and so Process should complete. We could still do the option in my previous comment if we want to be able to handle invalid JSON better in Process.

**Comment by jpmckinney** [comment]
> If Kingfisher Collect yields no data

So:

1. `file_worker` sets the collection's `data_type` based on incoming data. This never gets set if there is no data.
2. `compiler` will not set `compilation_started` if `data_type` is not set (because the strategies for records and releases are different - records can start compilation right away). This can occur if there's no data, or if the `close_collection` API endpoint is called before the `file_worker` gets to any of the collection's messages (in this latter case, `compiler` will set `compilation_started` once it reads a message published by `file_worker`). Anyway, when there's no data, `compilation_started` never gets set.
3. `finisher` checks `compilation_started` and won't set `completed_at` on the compiled collection if it's `False`.
4. The data registry needs the compiled collection to set `completed_at` to determine that Process has finished.

I think the only workaround is to check whether `expected_files_count` is 0.

**Comment by jpmckinney** [comment]
@yolile Feel free to re-open if you think we should pursue https://github.com/open-contracting/kingfisher-process/issues/354#issuecomment-2048555020
