### ISSUE TITLE
Docs do not appear to be generated properly

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/kingfisher-process#355]
If you look on the home page there appears to be minimal content: https://kingfisher-process.readthedocs.io/en/latest/get-started.html#

Pages linked to from ocdsdeploy appear to be missing e.g. https://kingfisher-process.readthedocs.io/en/latest/cli/local-load.html

I couldn't find a notice about transitioning the docs, but I might have missed something. If not, this may be an error.

**Comment by jpmckinney** [comment]
I've switched the docs back to the v1 branch, until we deploy the new version (and fill in its docs).
