### ISSUE TITLE
Add API endpoint for data registry integration for collection metadata

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/kingfisher-process#421]
The registry currently sets the following from Pelican:

```python
        job.date_from = parse_date(meta.get("published_from"))
        job.date_to = parse_date(meta.get("published_to"))
        job.license = meta.get("data_license") or ""
        job.ocid_prefix = meta.get("ocid_prefix") or ""
```

Pelican in `meta_data_aggregator.py` currently just takes the OCID prefix from the ocid of the first release/record, and the license (and publication policy) from the first package.

It also executes a single SQL query to get the published from/to dates.

We can add an endpoint to perform these simple, fast queries.

**Comment by yolile** [comment]
For reference, the queries are here https://github.com/open-contracting/pelican-backend/blob/80ce0549ea557a4bc1e87f5699b36ea20310479e/dataset/meta_data_aggregator.py#L39

**Comment by jpmckinney** [comment]
In #424 I'm also deleting an unused /collections/ list endpoint. It had a query to count the types of steps, which can be more easily rewritten as follows:

https://docs.djangoproject.com/en/5.0/ref/models/conditional-expressions/#conditional-aggregation

```
Collection.objects.aggregate(
    LOAD_steps_remaining=Count("pk", filter=Q(processing_steps__name=ProcessingStep.Name.LOAD)),
    COMPILE_steps_remaining=Count("pk", filter=Q(processing_steps__name=ProcessingStep.Name.COMPILE)),
    CHECK_steps_remaining=Count("pk", filter=Q(processing_steps__name=ProcessingStep.Name.CHECK)),
)
```

If we ever need it in future.
