### ISSUE TITLE
Docs - database tables

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#43]
Old docs had database tables section.

Add them back in here?

**Comment by odscjames** [comment]
There has been a request for this (so +1 basically), including with diagrams  - http://schemaspy.org/ was mentioned

**Comment by jpmckinney** [comment]
Seems to be closed by referenced commits, and anyhow, using a tool like SchemaSpy seems preferable to accepting the maintenance burden of documenting tables in static pages.
