### ISSUE TITLE
Add use-hosted page

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#44]
Like https://kingfisher-scrape.readthedocs.io/en/latest/use-hosted.html

Cross link the two pages

**Comment by odscjames** [comment]
We have a hosted page now - look into suitable cross links tho

**Comment by jpmckinney** [comment]
I'm assuming this is the hosted page? https://ocdskingfisher.readthedocs.io/en/latest/hosted.html#access-for-kingfisher-process I don't see any similar page in this repo's docs. There is not much to cross-link, so closing.
