### ISSUE TITLE
Create a new endpoint for collection_note

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher-process#443]
https://github.com/open-contracting/data-registry/issues/276  https://github.com/open-contracting/data-registry/issues/30#issuecomment-2048491058

**Comment by yolile** [comment]
From https://github.com/open-contracting/data-registry/issues/30#issuecomment-2048491058 I see we need notes from both, the original collection and the compiled one. @jpmckinney any particular structure preferred for returning them? 
1) Do we want to differentiate if the error comes from the compiled or original collection or are the messages themselves self-explanatory?
2) Do we want to return the `stored_at` time too?
3) A structure like 
```json
[
  {
    "note": "",
    "code": "",
    "data": {}
  }
]
```
should be enough?

Or maybe it would be easier if we already separate errors from warnings?, e.g. 

```json
{
  "warnings": [
    "note1", "note2", ...
  ],
  "errors": [
    {
      "note": "",
      "data": {}
    } 
  ]
}
```

**Comment by jpmckinney** [comment]
I think separating them could be easier for using the response. We can keep the original `code` value, and I think it's okay to use a two-value array instead of an object, e.g.

```json
{
  "WARNING": ["note", ...]
  "ERROR": [["note", {}], ...]
}
```

**Comment by jpmckinney** [comment]
Oh, and:

1. I think it's okay to mix them together.
2. We can leave it out.

**Comment by jpmckinney** [comment]
Note: There is one scenario where WARNING can have `data`, so let's use the same structure as ERROR.

**Comment by yolile** [comment]
> and I think it's okay to use a two-value array instead of an object,

Any reason for that? And note that, at least currently, we don't have any warnings with `data` set, so the second entry in the array for WARNING will always be {}

**Comment by jpmckinney** [comment]
A two-value array is easier to read if printed out verbatim (less boilerplate to skip), and easier to use, e.g.:

```python
for note, data in errors:
    note, data
```

instead of:

```python
for error in errors:
    error["note"], error["data"]
```

If we wanted to export the notes as CSV or print them out using [tabulate](https://pypi.org/project/tabulate/), we can just pass the array as-is without transformation, etc.

> we don't have any warnings with data set, so the second entry in the array for WARNING will always be {}

We don't currently, but it is possible: https://github.com/open-contracting/kingfisher-process/blob/20cfdc8d394f3c91445b147139403f8388b55d49/process/management/commands/file_worker.py#L95

**Comment by yolile** [comment]
Do we want the endpoint to a) return all notes (including INFO), b) receive the list of levels to include, or c) only Warnings and errors?
