### ISSUE TITLE
Lets break database normalisation to make some analyst queries much easier

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#46]
In the new system, if you want a list of all releases with the collection id=1 you do

```
select * from release 
join collection_file_item on collection_file_item.id = release.collection_file_item_id 
join collection_file on collection_file.id = collection_file_item.collection_file_id 
where collection_file.collection_id=1;
```

That's a pain and might be slow on the DB side.

Let's break normalisation and add to the release table a column collection_id, or maybe cached_collection_id to indicate it's not normalised.

Then the query becomes

```
select * from release where release.cached_collection_id=1;
```

(The downside of this would be if we ever moved releases between collections_file_items, or those between collection_files, or those between collections .... cos then we'd have to go back and do a lot of updating of the cached_collection_id column. But we don't do that! And I can't currently see a future need where we would!)

Would this help you, analysts?

**Comment by duncandewhurst** [comment]
Yes :-) https://github.com/open-contracting/kingfisher/issues/131

**Comment by yolile** [comment]
Yes!

**Comment by odscjames** [comment]
I see I argued against de-normalisation in the thread duncan linked :-P Now I'm much clearer about what we are doing with the the database structure I guess I'm happier about it.

**Comment by odscjames** [comment]
```
                     List of relations
 Schema |               Name               | Type |  Owner  
--------+----------------------------------+------+---------
 public | compiled_release_with_collection | view | ocdskfp
 public | record_with_collection           | view | ocdskfp
 public | release_with_collection          | view | ocdskfp
```

After discussion with @kindly created 3 new views. They are the same as the other tables, but with collection_id column.
