### ISSUE TITLE
HTTP API Endpoints - check required fields are there and sane, error with HTTP code if not

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#47]

**Comment by jpmckinney** [comment]
Did #42 close this? I haven't read the patch.

**Comment by odscjames** [comment]
No, this needs work.

**Comment by jpmckinney** [comment]
@odscjames Did #62 close this?

**Comment by jpmckinney** [comment]
Having read the code – this isn't done.

**Comment by odscjames** [comment]
No, we could do with more here but now #62 added a basic check to protect against empty submits I'm happy this is low priority. I haven't seen any problems related to this so far either, it was just for good code.

**Comment by jpmckinney** [comment]
When documenting the API in Swagger in #156 I (optimistically :)) added a few more required fields, which if not provided cause errors (as I understand). I agree that returning HTTP 400 (with a helpful message) instead of HTTP 500 is not a priority.

**Comment by jpmckinney** [comment]
Follow-up to https://github.com/open-contracting/kingfisher-process/issues/235#issuecomment-566521201: Need to error if `file_name` is not in the request.

**Comment by odscjames** [comment]
> Need to error if file_name is not in the request.

>>     maybe Process could assign a random filename if a blank one is passed?
> I think Process should return an error if no filename is passed #47. I don't know if Scrapy has any validation hooks we can use, so that spider authors can get an error during development.

I'd raise that we tend to be talking about error conditions that don't always come up during scraper development, so it's easy to miss cases like these. And when they do come up, they tend to be intermittent errors and we really want to see what they are so we can know how to handle them. So I'd rather process captured it with a random filename and logged the scrapers error than error and fail to record the useful data. (We can log that it used a random filename, for future scraper development)

**Comment by jpmckinney** [comment]
If `filename` can just as well be random, then why have the column at all?

I think it's best if a developer sees an error during scraper development rather than (1) when trying to send data to KF (my suggestion) or (2) when browsing through a log after sending data to KF (your suggestion), which they might not do as a regular practice (#242).

I've created an issue on scrape: https://github.com/open-contracting/kingfisher-scrape/issues/237

**Comment by jpmckinney** [comment]
Copying in an earlier note (code has changed since I made this note, so will need to double-check): require file_name, url, data_type, and one of local_file_name/file.

**Comment by jpmckinney** [comment]
Under the new [technical proposal](https://docs.google.com/document/d/1pED3ujU3SGMvBu9RYyM5atY6cEE_cmPt7XqgekE2jYs/edit), there will be a single web API endpoint for creating the collection #270). Other messages will be sent directly to RabbitMQ.

Unless we mis-implement that API endpoint, fields will be validated, so closing this issue.
