### ISSUE TITLE
User story: As an analyst I want to be able to explore package level metadata

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/kingfisher-process#53]
For example, I've just had a help-desk query asking for examples of licenses and publication policies.

These are captured at the [release and record package level](http://standard.open-contracting.org/latest/en/getting_started/publication_patterns/#packaging-releases-and-records) (e.g.: 

```json
{
"uri":"http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-01-planning.json",
"publishedDate":"2009-03-15T14:45:00Z",
"version":"1.1",
"extensions":[],
"publisher": {
        "scheme": "GB-COH",
        "uid": "09506232",
        "name": "Open Data Services Co-operative Limited",
        "uri": "http://standard.open-contracting.org/examples/"
    },
"license":"http://opendatacommons.org/licenses/pddl/1.0/",
"publicationPolicy":"https://github.com/open-contracting/sample-data/",
"releases":[{"...":"..."}]
}
```

I would like to be able to run easy queries to find out:

* All the unique URLs given for `license` or `publicationPolicy` and the publisher associated with those (I would *anticipate* these are constants for most publishers);
* Which publishers are declaring use of a particular extension;
* The correlations between `publishedDates` and `version` (to see if people are switching to new versions over time / retroactively updating versions)

It may be that the package data is already stored at file level - so this is just a case of guidance on the queries to run? I anticipate though there might be some optimisation potential here if the 'blob' of JSON stored is the whole release package, rather than *just* the outer package data.

**Comment by jpmckinney** [comment]
@odscjames As far as I know, there is a package_data table, so can this be closed?
