### ISSUE TITLE
User story: As an analyst I want to check how many contracting processes a given group of fields is present in

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#54]
There was a request from @LindseyAM to check which of the [indicators](https://docs.google.com/spreadsheets/d/1j-Y0ktZiOyhZzi-2GSabBCnzx6fF5lv8h1KYwi_Q9GM/edit#gid=612001000) in the [Using it, not losing it report](https://www.open-contracting.org/resources/using-it/) could be calculated from the NSW Australia data.

Rather than crafting individual queries for each indicator (i.e. set of OCDS fields we're interested in) it would be good to have a generic way of checking what proportion of contracting processes a given group of fields is present in.

Whilst the mapping of indicators to OCDS fields requires some further work, this is a type of question we'll want to answer using ocdsdata.

My initial exploration yesterday ruled out:

* Simply downloading all releases for the publisher from the `data` table and iterating through them in Python ~~(far too slow for 80,000 records)~~ since for some publishers that could be many gigabytes of data
* Expanding all arrays in the OCDS schema to create a single mega table to run queries against (also too slow)

I suspect the answer might lie in creating intermediary tables, e.g. one for each array in OCDS, and using sub queries to get a list of ocids for which all the fields we're interested in are present, but I'd like to invite views from those with better SQL/postgres skills than me!

@kindly @yolile @Tim0th1 @timgdavies @jpmckinney

**Comment by jpmckinney** [comment]
We'll raise this use case as part of the data quality tools work. Essentially, it's about reporting the number / proportion of compiled releases all pass a given set of checks (e.g. field X present, field Y present, field Z present, etc.).

**Comment by duncandewhurst** [comment]
Just noting that @kindly did develop a query to answer this question, which generated an output like:

| ocid | fields |
| -- | -- |
| ocds-123456-001 | [ocid,id,date,language,tender/id,tender/procurementMethod...] |
| ocds-123456-002 | [ocid,id,date,language,awards/id,awards/value...] |

It hasn't been integrated into kingfisher views yet, but could possibly be added there.

**Comment by jpmckinney** [comment]
Where is this query, in case it can be reused?

I think reporting on these quality checks should all be done in one system, unless there is a clear need to have it expressed in a view.

**Comment by jpmckinney** [comment]
I think I found the query at the bottom of the feedback report notebook. The approach is likely to be very similar (essentially: querying coverage results to calculate the check).
