### ISSUE TITLE
For Coverage reports, need to have in DB list of all possible fields.

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#57]
This was discussed at Montreal Aug. It comes from #68

The main code should be written into OCDSkit - issue here: https://github.com/open-contracting/ocdskit/issues/55

As soon as that is done, we should create a "schema_felds" table like the one in pull request #68.

Every time we load some data, we should generate the field mapping for the data's specific extensions and store that in the new "schema_fields" table.  

(Noting as well that one set of data might have bits of data with different extension combinations. In this case, cache the fields for them all).

We can do this now even thought OCDSData itself won't be using the contents. Because analysts can write SQL by hand to use this data, it will still be useful.

**Comment by jpmckinney** [comment]
It's not clear to me that we need the DB list in the database. Closing as we need to back up and think through how/where we want to implement this.
