### ISSUE TITLE
Comparing a compiledRelease with the individual releases it was compiled from

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/kingfisher-process#59]
@jpmckinney @robredpath and I briefly discussed whether it was necessary to support easier analysis across compiledReleases created by a transformation in Kingfisher and the individual releases which they were compiled from by having them under the same collection in the database, or whether it would be OK to have these loaded into separate collections in the database.

I reviewed the OCDS data queries, reports and visualization document and I don't think any of the queries expressed there would require this functionality, however I think this could be a useful feature for other users of the data where the original publisher only publishes releases.

For example, answering the question "did the contract value change after the original award?" would be easier to answer by comparing the compiledRelease with a 'contract' release, than it would be to answer from the individual releases alone (where updates to the contract value could occur under multiple release tags and where subsequent releases may choose to omit the contract value).

The other use I can think of for distinguishing between kingfisher-compiled releases and publisher-compiled releases (as opposed to just loading compiled releases from outside the DB and not knowing whether they were compiled by Kingfisher or the publisher) is to answer questions of the type "how many publishers are using the correct tag for compiled releases" etc.

**Comment by jpmckinney** [comment]
The discussion is different from the issue title. From the perspective of the discussion, I think this issue is closed.
