### ISSUE TITLE
Most print statements should be replaced by logging calls

### ISSUE THREAD

**Issue by tian2992** [open-contracting/kingfisher-process#60]
Logging should be handled better, at the very least be possible to implement a flag for -verbose -quiet or for specific parts of the pipeline and/or redirect to logfiles.

- [ ] detecting print candidates
- [ ] classify the logging priority/context 
- [ ] do the switcheroo
- [x] default config settings
- [ ] file / other config settings
- [ ] flags

**Comment by odscjames** [comment]
Note this issue might relate to #21
