### ISSUE TITLE
upgrade-1-0-to-1-1: Store warnings (in collection_note table)

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#67]
Under certain conditions, the library may give a warning.

@jpmckinney Do you have test data that makes the library give a warning?

Make sure the warning is saved to the new collection somewhere. Probably warnings column in the files table, but check that.

**Comment by jpmckinney** [comment]
Here's a test that issues a warning: https://github.com/open-contracting/ocdskit/blob/master/tests/commands/test_upgrade.py#L41

When upgrading this file: https://github.com/open-contracting/ocdskit/blob/master/tests/fixtures/release_1.0.json
