### ISSUE TITLE
run-checks and run-transforms performance

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#69]
These can take a long time to work through data that is already checked/transformed, and thus when you run them nothing actually happens for a bit - can we speed that up?

**Comment by odscjames** [comment]
Currently we load each row individually in Python. I''m pretty certain it will be faster to do this in the database. Load releases that need doing with something like: 

```
SELECT release_with_collection.id FROM release_with_collection 
LEFT JOIN release_check ON release_check.release_id = release_with_collection.id
LEFT JOIN release_check_error ON release_check_error.release_id = release_check_error.id
WHERE release_with_collection.collection_id = 1 AND release_check.id IS NULL AND release_check_error.id IS NULL

```

**Comment by odscjames** [comment]
Once https://github.com/open-contracting/kingfisher-process/pull/83 is merged we can speed up run-transforms by simply checking the store_end_at field, and if it's set we know there is nothing to do.

**Comment by odscjames** [comment]
> Once #83 is merged we can speed up run-transforms by simply checking the store_end_at field, and if it's set we know there is nothing to do.

Transforms now do nothing if store_end_at is set, faster!

**Comment by jpmckinney** [comment]
@odscjames Is this issue closed? If not, what's left?

**Comment by jpmckinney** [comment]
Noting that this will be resolved in the Django branch by not using the database as a queue.
