### ISSUE TITLE
Local-Load command should have option to mark collection store ended after load, optional flag.

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#76]
For ease of use when doing local loads, instead of using the command from #75

Marking a collection store as done should be un-undoable - tho it's only a column in the database, other operations might have already started and we don't want to try and take those back. So it should be optional, and off by default.

**Comment by duncandewhurst** [comment]
I've fallen foul of forgetting to end the store after running a local load (although it is documented directly under the local load command in the docs, I still seem capable of forgetting it).

@odscjames and I discussed whether we should add a prompt to the end of the local load command to remind users to end the store, or whether the command should automatically end the store after running:

> duncand is there a reason why it doesn't just automatically end the store once the last file the directory has been loaded?
> James you might want to add more than one dir
> duncand I'd by tempted to err on the side of making the tool as simple as possible, even if it requires the user to get their source files together into one directory to use it
> James what if the user wanted to load more than one dir where each dir contained files of different types?
> James would a prompt at the end of local-load command to run that if finished be good?
> duncand I think we've generally treated different types as separate sources (e.g. we have paraguay_dncp_releases and paraguay_dncp_records etc.) I'm not sure what the benefit of having multiple types in one collection would be, but i can think of some downsides (possible double counting etc.)

I think having the flag on by default would make most sense, but I'm open to being persuaded otherwise if others have examples of times when they have needed to run the local load command on several directories.

**Comment by jpmckinney** [comment]
I don't have a strong opinion in terms of the default.

If it is off by default, we can update the docs so that the first example sets it 'on'. That way, when copy-pasting template commands, users are very likely to get the behavior they want.

**Comment by romifz** [comment]
I've never had the need of using more than one directory but I agree that someone may face that scenario sometime - ending the loading by default and having a flag to disable that behaviour sounds like the best option to me.

**Comment by pindec** [comment]
I've also forgotten to end a local load a few times - it's a command I don't use often and therefore it's difficult to remember the additional command required after the load itself. However, I think we may still need the multiple-directories functionality.
I agree with @duncandewhurst and @romifz: end local load after running by default, override default with a flag.

**Comment by yolile** [comment]
I agree with the auto ended by default, too

**Comment by odscjames** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change Kingfisher Local Load command so by default it ends collection store (flag to leave it open)](https://trello.com/c/GzcMuDuy/57-change-kingfisher-local-load-command-so-by-default-it-ends-collection-store-flag-to-leave-it-open)

**Comment by odscjames** [comment]
Seems clear winner then; end collection by default, flag to leave open :-)

**Comment by jpmckinney** [comment]
Closed by #178
