### ISSUE TITLE
When making package_data, don't remove both 'records' and 'releases' automatically!

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#81]
https://github.com/open-contracting/kingfisher-process/blob/master/ocdskingfisherprocess/store.py#L156

            package_data = {}
            if not data_type == 'release' and not data_type == 'compiled_release':
                for key, value in json_data.items():
                    if key not in ('releases', 'records'):
                        package_data[key] = value

The problem is, we now have a source that is meant to be a records_package type. It has the 'records' array as it's meant to ... but it also has the 'releases' array! Ideally, we'd like KF to store that, so the checks can go "extra fields alert!". But this code always strips both out!

Replace this with code that strips out  'releases' key OR  'records' key depending on what data_type.

(The source is moldova_records BTW)

**Comment by jpmckinney** [comment]
`moldova_records` no longer exists, and this should hopefully never occur again. If it does, then in Kingfisher Collect https://github.com/open-contracting/kingfisher-collect/issues/329, we can default to one, and give the user the option to select the other.
