### ISSUE TITLE
Default checks on/off per collection can be smarter

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#87]
At the moment we have config options - default checks to on or off for each collection?

BUT in the future - see https://github.com/open-contracting/kingfisher/issues/296 - we are going to have a standard transform pipeline:

*  raw data ->
*  upgraded to 1.1 ->
*  compile releases

We don't need checks on by default for each stage in the pipeline - by default we probably want them off for the first stage, on for the second stage, and off for the third stage* - we think? @duncandewhurst to confirm please!

(Note it will always be possible to turn checks on later if for some reason you do want them - this is about what the *default* options should be)

ps * Checks don't do anything for compiled releases at the moment. I'll make a new issue to confirm that.

**Comment by jpmckinney** [comment]
Everything should be "off" by default. It's cognitively simpler than having to remember which things are on by default and which are off.

Configuration will ensure that analysts don't need to care / worry about what the defaults are, and that their desired behavior is configured.

**Comment by odscjames** [comment]
I think we're using different definitions of "Default" here - sorry. I agree that all these options should be off by default in the code and we'll turn them to a sensible standard set of operations for our analysts in our server config. I was using default here to mean " a sensible standard set of operations for our analysts" - that was confusing.

The point of this issue is : I suspect we can be cleverer about that "sensible standard set of operations for our analysts", and only have checks on some of the time, and I wanted to ask the analysts about that.

**Comment by jpmckinney** [comment]
I suspect the minimum is "raw data" – as we don't want to e.g. share CoVE reports about the `parties` array if they provide 1.0 data, which would have no `parties` array. From my perspective, the need to share CoVE reports after upgrade/compile are fairly narrow, but analysts can confirm.

**Comment by duncandewhurst** [comment]
I think checks only on the raw data/original collection should be fine.

**Comment by odscjames** [comment]
Now done, deployed, and all existing collections updated with this.
