### ISSUE TITLE
Should checks do anything with compiled releases from transforms?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#88]
The Cove Checks.

At the moment, they don't run on compiled releases that we create from a transform.

At the moment, they only run on releases and records (Note if these contain complied releases they will be checked)

(Realised when typing https://github.com/open-contracting/kingfisher-process/issues/87 )

**Comment by pindec** [comment]
Running cove checks on our generated compiled releases would support some cross-checking between publisher's own records/compiledReleases and ours to highlight potential issues with either.
So it would be helpful, but not essential.

**Comment by odscjames** [comment]
> Should checks do anything with compiled releases from transforms?

Yes - because if a sources complied releases differed from the releases we complied, we still want to run checks against our compiled releases to see if there are any data errors.

The issue of knowing "if a sources complied releases differed from the releases we complied" is a separate issue that I will create now.

**Comment by jpmckinney** [comment]
In [more recent discussions](https://docs.google.com/document/d/17BY8RLrX0rTp7K0zypthw3Zz7XxaBlxoaBHiPlFZHGU/edit#bookmark=id.874onldmhevw) over the summer, analysts expressed that they only need the checks of the original data, and that there isn't much need to check compiled releases (similar to earlier comment about helpful but not essential). Closing as this use case has not had any demand.
