### ISSUE TITLE
How can we tell if a sources compiled releases differ from the releases we compile ourself via transform?

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#93]
Presumably we can't just do a simple compare - some differences (a small extra field) will be fine. While other differences will not be fine.

We suspect this question is a can of worms.

(Realised when doing https://github.com/open-contracting/kingfisher-process/issues/88 )

**Comment by jpmckinney** [comment]
I think the only differences that are okay to ignore are differences in the id, date, and tag.

All other differences are relevant (extra fields are definitely relevant).

**Comment by jpmckinney** [comment]
Related: #59

**Comment by jpmckinney** [comment]
Is there an issue here, or is it just a question?
